name = "tuist-worker-production"
main = "src/index.js"
compatibility_date = "2025-01-08"
routes = [
  "https://tuist.dev/api/cas/*"
]

[[kv_namespaces]]
binding = "CAS_CACHE"
id = "2adf75e070fd43cabee0be83cb4a562d"
preview_id = "2f1058911a144cab9c8816478e03f4e2"

[[kv_namespaces]]
binding = "CAS_CACHE_BLOBS"
id = "TODO: Add production KV namespace ID for blobs"
preview_id = "a1fee20723214cc5829176721e14f00d"

[dev]
port = 8787

# Development environment
[env.development]
name = "tuist-worker-development"
[[env.development.kv_namespaces]]
binding = "CAS_CACHE"
id = "2f1058911a144cab9c8816478e03f4e3"
[[env.development.kv_namespaces]]
binding = "CAS_CACHE_BLOBS"
id = "a1fee20723214cc5829176721e14f00e"

# Staging environment
[env.staging]
name = "tuist-worker-staging"
routes = [
  "https://staging.tuist.dev/api/cas/*"
]
[[env.staging.kv_namespaces]]
binding = "CAS_CACHE"
id = "4eecec1f40f84dc1bd8233944b835934"
[[env.staging.kv_namespaces]]
binding = "CAS_CACHE_BLOBS"
id = "273a93203b8c469e8f193cdd24ffd64f"

# Canary environment
[env.canary]
name = "tuist-worker-canary"
routes = [
  "https://canary.tuist.dev/api/cas/*"
]
[[env.canary.kv_namespaces]]
binding = "CAS_CACHE"
id = "c95cdd9d54fa49b89465b3993c298186"
[[env.canary.kv_namespaces]]
binding = "CAS_CACHE_BLOBS"
id = "cb953df9fb6d42fa8fdca17f06287ba7"
