{{- $password := include "rack-edge.vrrpPassword" . }}
apiVersion: v1
kind: Secret
metadata:
  name: rack-edge-{{ include "rack-edge.site" . }}-vrrp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rack-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ $password | quote }}
  authentication.conf: |
    authentication {
      auth_type PASS
      auth_pass {{ $password }}
    }
