#!/usr/bin/env bash
# mise description="Re-creates and migrates the database and seeds it with data"

set -euo pipefail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

$SCRIPT_DIR/drop
$SCRIPT_DIR/create
$SCRIPT_DIR/migrate
$SCRIPT_DIR/seed
