{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typesense.serviceAccountName" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
{{- end }}
