# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `raabro` gem.
# Please instead update this file by running `bin/tapioca gem raabro`.

# source://raabro//lib/raabro.rb#3
module Raabro
  extend ::Raabro::ModuleMethods

  class << self
    # source://raabro//lib/raabro.rb#596
    def included(target); end

    # Black       0;30     Dark Gray     1;30
    # Blue        0;34     Light Blue    1;34
    # Green       0;32     Light Green   1;32
    # Cyan        0;36     Light Cyan    1;36
    # Red         0;31     Light Red     1;31
    # Purple      0;35     Light Purple  1;35
    # Brown       0;33     Yellow        1;33
    # Light Gray  0;37     White         1;37
    #
    # source://raabro//lib/raabro.rb#618
    def pp(tree, depth = T.unsafe(nil), opts = T.unsafe(nil)); end
  end
end

# source://raabro//lib/raabro.rb#7
class Raabro::Input
  # @return [Input] a new instance of Input
  #
  # source://raabro//lib/raabro.rb#12
  def initialize(string, offset = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#36
  def at(i); end

  # source://raabro//lib/raabro.rb#19
  def match(str_or_regex); end

  # Returns the value of attribute offset.
  #
  # source://raabro//lib/raabro.rb#9
  def offset; end

  # Sets the attribute offset
  #
  # @param value the value to set the attribute offset to.
  #
  # source://raabro//lib/raabro.rb#9
  def offset=(_arg0); end

  # Returns the value of attribute options.
  #
  # source://raabro//lib/raabro.rb#10
  def options; end

  # Returns the value of attribute string.
  #
  # source://raabro//lib/raabro.rb#9
  def string; end

  # Sets the attribute string
  #
  # @param value the value to set the attribute string to.
  #
  # source://raabro//lib/raabro.rb#9
  def string=(_arg0); end

  # source://raabro//lib/raabro.rb#31
  def tring(l = T.unsafe(nil)); end
end

# source://raabro//lib/raabro.rb#240
module Raabro::ModuleMethods
  # source://raabro//lib/raabro.rb#242
  def _match(name, input, parter, regex_or_string); end

  # source://raabro//lib/raabro.rb#279
  def _narrow(parser); end

  # source://raabro//lib/raabro.rb#286
  def _parse(parser, input); end

  # source://raabro//lib/raabro.rb#265
  def _quantify(parser); end

  # source://raabro//lib/raabro.rb#438
  def all(name, input, parser); end

  # source://raabro//lib/raabro.rb#333
  def alt(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#378
  def altg(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#457
  def eseq(name, input, startpa, eltpa, seppa = T.unsafe(nil), endpa = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#457
  def jseq(name, input, startpa, eltpa, seppa = T.unsafe(nil), endpa = T.unsafe(nil)); end

  # Returns the value of attribute last.
  #
  # source://raabro//lib/raabro.rb#529
  def last; end

  # Sets the attribute last
  #
  # @param value the value to set the attribute last to.
  #
  # source://raabro//lib/raabro.rb#529
  def last=(_arg0); end

  # source://raabro//lib/raabro.rb#594
  def make_includable; end

  # source://raabro//lib/raabro.rb#531
  def method_added(name); end

  # source://raabro//lib/raabro.rb#422
  def nott(name, input, parser); end

  # source://raabro//lib/raabro.rb#540
  def parse(input, opts = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#413
  def ren(name, input, parser); end

  # source://raabro//lib/raabro.rb#413
  def rename(name, input, parser); end

  # source://raabro//lib/raabro.rb#383
  def rep(name, input, parser, min, max = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#568
  def reparse_for_error(input, opts, t); end

  # source://raabro//lib/raabro.rb#586
  def rewrite(tree); end

  # source://raabro//lib/raabro.rb#579
  def rewrite_(tree); end

  # source://raabro//lib/raabro.rb#260
  def rex(name, input, regex_or_string); end

  # source://raabro//lib/raabro.rb#295
  def seq(name, input, *parsers); end

  # source://raabro//lib/raabro.rb#255
  def str(name, input, string); end
end

# source://raabro//lib/raabro.rb#42
class Raabro::Tree
  # @return [Tree] a new instance of Tree
  #
  # source://raabro//lib/raabro.rb#49
  def initialize(name, parter, input); end

  # source://raabro//lib/raabro.rb#60
  def c0; end

  # source://raabro//lib/raabro.rb#61
  def c1; end

  # source://raabro//lib/raabro.rb#62
  def c2; end

  # source://raabro//lib/raabro.rb#63
  def c3; end

  # source://raabro//lib/raabro.rb#64
  def c4; end

  # Returns the value of attribute children.
  #
  # source://raabro//lib/raabro.rb#47
  def children; end

  # Sets the attribute children
  #
  # @param value the value to set the attribute children to.
  #
  # source://raabro//lib/raabro.rb#47
  def children=(_arg0); end

  # source://raabro//lib/raabro.rb#65
  def clast; end

  # @return [Boolean]
  #
  # source://raabro//lib/raabro.rb#67
  def empty?; end

  # source://raabro//lib/raabro.rb#166
  def even_children; end

  # source://raabro//lib/raabro.rb#171
  def extract_error; end

  # source://raabro//lib/raabro.rb#112
  def gather(name = T.unsafe(nil), acc = T.unsafe(nil)); end

  # Returns the value of attribute input.
  #
  # source://raabro//lib/raabro.rb#44
  def input; end

  # Sets the attribute input
  #
  # @param value the value to set the attribute input to.
  #
  # source://raabro//lib/raabro.rb#44
  def input=(_arg0); end

  # Returns the value of attribute length.
  #
  # source://raabro//lib/raabro.rb#46
  def length; end

  # Sets the attribute length
  #
  # @param value the value to set the attribute length to.
  #
  # source://raabro//lib/raabro.rb#46
  def length=(_arg0); end

  # source://raabro//lib/raabro.rb#216
  def line_and_column(offset); end

  # source://raabro//lib/raabro.rb#96
  def lookup(name = T.unsafe(nil)); end

  # Not "lookup all errors" but "lookup all error", in other
  # words lookup the point up until which the parser stopped (not
  # consuming all the input)
  #
  # source://raabro//lib/raabro.rb#208
  def lookup_all_error; end

  # source://raabro//lib/raabro.rb#193
  def lookup_error(stack = T.unsafe(nil)); end

  # Returns the value of attribute name.
  #
  # source://raabro//lib/raabro.rb#44
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # source://raabro//lib/raabro.rb#44
  def name=(_arg0); end

  # source://raabro//lib/raabro.rb#85
  def nonstring(l = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#161
  def odd_children; end

  # Returns the value of attribute offset.
  #
  # source://raabro//lib/raabro.rb#46
  def offset; end

  # Sets the attribute offset
  #
  # @param value the value to set the attribute offset to.
  #
  # source://raabro//lib/raabro.rb#46
  def offset=(_arg0); end

  # Returns the value of attribute parter.
  #
  # source://raabro//lib/raabro.rb#47
  def parter; end

  # Sets the attribute parter
  #
  # @param value the value to set the attribute parter to.
  #
  # source://raabro//lib/raabro.rb#47
  def parter=(_arg0); end

  # source://raabro//lib/raabro.rb#77
  def prune!; end

  # ((-1 error,)) 0 nomatch, 1 success
  #
  # source://raabro//lib/raabro.rb#45
  def result; end

  # ((-1 error,)) 0 nomatch, 1 success
  #
  # source://raabro//lib/raabro.rb#45
  def result=(_arg0); end

  # source://raabro//lib/raabro.rb#83
  def strim; end

  # source://raabro//lib/raabro.rb#87
  def strind; end

  # source://raabro//lib/raabro.rb#82
  def string; end

  # source://raabro//lib/raabro.rb#87
  def stringd; end

  # source://raabro//lib/raabro.rb#89
  def stringpd; end

  # source://raabro//lib/raabro.rb#83
  def strinp; end

  # source://raabro//lib/raabro.rb#89
  def strinpd; end

  # source://raabro//lib/raabro.rb#125
  def subgather(name = T.unsafe(nil), acc = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#105
  def sublookup(name = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#72
  def successful_children; end

  # source://raabro//lib/raabro.rb#93
  def symbod; end

  # source://raabro//lib/raabro.rb#92
  def symbol; end

  # source://raabro//lib/raabro.rb#93
  def symbold; end

  # source://raabro//lib/raabro.rb#132
  def to_a(opts = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#149
  def to_s(depth = T.unsafe(nil), io = T.unsafe(nil)); end

  # source://raabro//lib/raabro.rb#233
  def visual(line, column); end
end

# source://raabro//lib/raabro.rb#5
Raabro::VERSION = T.let(T.unsafe(nil), String)
