{{- if and (eq .Values.objectStorage.mode "external") .Values.objectStorage.external.managedSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tuist.componentName" (dict "root" . "component" "object-storage-external-secrets") }}
  labels:
    {{- include "tuist.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.objectStorage.external.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.objectStorage.external.externalSecrets.storeRef.name | default "onepassword" }}
    kind: {{ .Values.objectStorage.external.externalSecrets.storeRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "tuist.componentName" (dict "root" . "component" "object-storage-external-secrets") }}
    creationPolicy: Owner
  data:
    - secretKey: object-storage-access-key
      remoteRef:
        key: "{{ .Values.objectStorage.external.externalSecrets.accessKey.item | default "S3_CREDENTIALS" }}/{{ .Values.objectStorage.external.externalSecrets.accessKey.field | default "access_key_id" }}"
    - secretKey: object-storage-secret-key
      remoteRef:
        key: "{{ .Values.objectStorage.external.externalSecrets.secretKey.item | default "S3_CREDENTIALS" }}/{{ .Values.objectStorage.external.externalSecrets.secretKey.field | default "secret_access_key" }}"
{{- end }}
