{{- if .Values.processor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuist.componentName" (dict "root" . "component" "processor") }}
  labels:
    {{- include "tuist.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  type: ClusterIP
  selector:
    {{- include "tuist.componentLabels" (dict "root" . "component" "processor") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.processor.service.port }}
      targetPort: {{ .Values.processor.service.targetPort }}
{{- end }}
