{{- if and .Values.registry.enabled .Values.registry.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tuist.componentServiceAccountName" (dict "root" . "component" "registry") }}
  labels:
    {{- include "tuist.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  {{- with .Values.registry.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.registry.automountServiceAccountToken }}
{{- end }}
