{{- if and .Values.server.enabled .Values.server.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuist.serverHeadlessServiceName" . }}
  labels:
    {{- include "tuist.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "tuist.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: http
      port: {{ .Values.server.service.targetPort }}
      targetPort: {{ .Values.server.service.targetPort }}
{{- end }}
