creation_rules:
  - path_regex: secrets/production\.yaml$
    age: >-
      age1y5rlt84laf2m9fjys09zmwzt6rnmevs5h4a5y3qprjz5y2qfkg8queqv0v
  - path_regex: secrets/staging\.yaml$
    age: >-
      age1y2dw7yakkpjfem5nydfwhsqkgh2009dt2z26fxx0rzzsj7etucxs0qdfs2
  - path_regex: secrets/canary\.yaml$
    age: >-
      age160kt0acj7c08pgzxx6z4g703x50exy3czpeqfy2fhztx7aeewvcsjgang7
