Mimic.copy(Stripe.BillingPortal.Session)
Mimic.copy(Stripe.Customer)
Mimic.copy(TuistCloud.Billing)
Mimic.copy(TuistCloud.Environment)
Mimic.copy(TuistCloud.Storage)
Mimic.copy(TuistCloud.Time)
Mimic.copy(TuistCloud.Date)
Mimic.copy(TuistCloud.Slack)
Mimic.copy(TuistCloud.CommandEvents)
Mimic.copy(Req)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(TuistCloud.Repo, :manual)
