Mimic.copy(Hammer)
Mimic.copy(Req)
Mimic.copy(Stripe.BillingPortal.Session)
Mimic.copy(Stripe.Checkout.Session)
Mimic.copy(Stripe.Customer)
Mimic.copy(Stripe.PaymentMethod)
Mimic.copy(Stripe.Request)
Mimic.copy(Stripe.Subscription)
Mimic.copy(TuistCloud.Accounts)
Mimic.copy(TuistCloud.Billing)
Mimic.copy(TuistCloud.CommandEvents)
Mimic.copy(TuistCloud.Date)
Mimic.copy(TuistCloud.Environment)
Mimic.copy(TuistCloud.Native)
Mimic.copy(TuistCloud.Repo)
Mimic.copy(TuistCloud.Slack)
Mimic.copy(TuistCloud.Storage)
Mimic.copy(TuistCloud.Time)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(TuistCloud.Repo, :manual)
