Mimic.copy(Hammer)
Mimic.copy(Phoenix.LiveView.Lifecycle)
Mimic.copy(Req)
Mimic.copy(Bcrypt)
Mimic.copy(JOSE)
Mimic.copy(JOSE.JWK)
Mimic.copy(JOSE.JWS)
Mimic.copy(JOSE.JWT)
Mimic.copy(Stripe.BillingPortal.Session)
Mimic.copy(Stripe.Checkout.Session)
Mimic.copy(Stripe.Customer)
Mimic.copy(Stripe.PaymentMethod)
Mimic.copy(Stripe.Request)
Mimic.copy(Stripe.Subscription)
Mimic.copy(Tuist.Accounts)
Mimic.copy(Tuist.Billing)
Mimic.copy(Tuist.CommandEvents)
Mimic.copy(Tuist.Date)
Mimic.copy(Tuist.Environment)
Mimic.copy(Tuist.Native)
Mimic.copy(Tuist.Repo)
Mimic.copy(Tuist.Slack)
Mimic.copy(Tuist.Storage)
Mimic.copy(Tuist.Time)
Mimic.copy(Tuist.Guardian)
Mimic.copy(Tuist.Authentication)
Mimic.copy(Tuist.Projects)
Mimic.copy(Tuist.Base64)
Mimic.copy(Tuist.VCS.Reporter)
Mimic.copy(Tuist.GitHub.Client)
Mimic.copy(Tuist.GitHub.Releases)
Mimic.copy(Tuist.GitHub.TokenStorage)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Tuist.Repo, :manual)
Credo.Application.start([], [])
