{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-operator-token
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: cloudflare-operator-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.externalSecret.itemTitle }}
        property: token
{{- end }}
