author: xcbuddy
module: xcbuddykit
github_url: https://github.com/xcbuddy/xcbuddy
copyright: 'Copyright © 2018 Pedro Piñera. All rights reserved.'
readme: README.md
documentation: guides/*.md
skip_undocumented: true
theme: fullwidth
xcodebuild_arguments: [-workspace, 'xcbuddy.xcworkspace', -scheme, 'xcbuddykit']
sdk: macosx
clean: true
min_acl: internal
custom_categories:
  - name: Commands
    children:
      - Command
      - CommandRegistry
      - DumpCommand
      - UpdateCommand
      - CommandsContext
  - name: Models
    children:
      - BuildConfiguration
      - BuildFiles
      - Target
      - Config
      - Workspace
      - Scheme
      - Project
      - Settings
      - Platform
      - BuildPhase
      - Product
  - name: Errors
    children:
      - ErrorHandler
      - FatalError
