author: Tuist
github_url: https://github.com/tuist/tuist
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
output: docs
module: ProjectDescription
clean: true
xcodebuild_arguments:
  - -project
  - tuist.xcodeproj
  - -scheme
  - tuist-Package
swift_version: '5.0.1'
min_acl: public
readme: README.md
custom_categories:
  - name: Worksaces
    children:
      - Workspace
      - Project
  - name: Targets
    children:
      - Target
      - TargetDependency
      - CoreDataModel
      - Headers
      - Platform
      - Product
  - name: Settings
    children:
      - Settings
      - BuildConfiguration
      - Configuration
  - name: Schemes
    children:
      - Scheme
      - RunAction
      - TestAction
      - BuildAction
      - Arguments
