version = 1

[merge]
automerge_label = "automerge"

[merge.automerge_dependencies]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]

[update]
always = true
require_automerge_label = false
ignored_usernames = ["dependabot"]