version = 1

[update]
always = true
require_automerge_label = false
ignored_usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"