inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml
require:
  - rubocop-rake
  - rubocop-minitest

Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Lint/MissingSuper:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Gemfile
    - Rakefile
    - projects/fourier/**/*.rb
  Exclude:
    - vendor/**/*
