inherit_gem:
  rubocop-shopify: rubocop.yml
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-rake
  - rubocop-minitest

Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Lint/MissingSuper:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Gemfile
    - Rakefile
    - projects/fourier/**/*.rb
    - projects/lab-api/**/*.rb

  Exclude:
    - vendor/**/*
    - projects/website/node_modules/**/*
    - projects/tuist/fixtures/**/*
    - projects/lab-api/node_modules/**/*
    - projects/lab-api/vendor/**/*
    - projects/lab-api/db/schema.rb
    - projects/lab-api/bin/**/*
