inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - features/**/*
    - fixtures/**/*
    - .build/**/*
    - .vscode/**/*
    - assets/**/*
    - build/**/*
    - Carthage/**/*
    - Sources/**/*
    - Tests/**/*
    - .github/**/*
    - website/**/*
    - next/**/*
