included:
  - Sources
excluded:
  - Assets
  - Fixtures
  - Tests
  - .build
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
line_length:
  warning: 150
  error: 170
identifier_name:
  min_length:
    error: 1
    warning: 1
function_parameter_count:
  warning: 7
  error: 8
