included:
  - Sources
excluded:
  - Tests
  - .build
disabled_rules:
  - trailing_whitespace
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
  - function_parameter_count
  - function_body_length
  - identifier_name
line_length:
  warning: 150
  error: 170
  ignores_interpolated_strings: true
  ignores_comments: true
  ignores_urls: true
identifier_name:
  min_length:
    error: 1
  excluded:
    - id
type_name:
  min_length:
    warning: 3
    error: 1
  excluded:
    - Up
