workflows:
  lint:
    name: Lint
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - github_credentials
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Generate the Tuist project
        script: mise x -- tuist generate --no-binary-cache
      - name: Lint
        script: mise run lint
    triggering: &branch_triggering
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: true
  spm_build:
    name: SPM Build
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - github_credentials
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Build
        script: swift build --configuration debug
    triggering:
      <<: *branch_triggering
  build_docs:
    name: Build Documentation
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Install dependencies
        script: mise run install
      - name: Generate manifest docs
        script: mise run docs:generate-manifests-docs
      - name: Build the documentation
        script: mise run docs:build
    triggering:
      <<: *branch_triggering
  unit_tests:
    name: Unit tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistUnitTests
    triggering:
      <<: *branch_triggering
  cache:
    name: Cache
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Print hashes
        script: mise x -- tuist cache --print-hashes
      - name: Cache
        script: mise x -- tuist cache
    triggering: &main_triggering
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
      cancel_previous_builds: true
  deploy_docs:
    name: Deploy Documentation
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=cc0237353f2f825680b0463629cd4a86" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Install dependencies
        script: mise run install
      - name: Generate manifest docs
        script: mise run docs:generate-manifests-docs
      - name: Build the documentation
        script: mise run docs:build
      - name: Deploy to Cloudflare Pages
        script: |
          mise x npm:wrangler@latest -- wrangler pages deploy --commit-hash $CM_COMMIT --branch $CM_BRANCH --project-name tuist-docs docs/.vitepress/dist
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
      cancel_previous_builds: true

  # FIXME: Merge all the schemes into one and remove all of the following workflows
  tuist_automation_acceptance_tests:
    name: Tuist automation acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistAutomationAcceptanceTests
    triggering:
      <<: *branch_triggering

  tuist_dependencies_acceptance_tests:
    name: Tuist dependencies acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Set up new keychain
        script: |
          TMP_DIRECTORY=$(mktemp -d)
          KEYCHAIN_PATH=$TMP_DIRECTORY/keychain.keychain
          KEYCHAIN_PASSWORD=$(uuidgen)
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistDependenciesAcceptanceTests
    triggering:
      <<: *branch_triggering

  tuist_generator_acceptance_tests:
    name: Tuist generator acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistGeneratorAcceptanceTests
    triggering:
      <<: *branch_triggering

  tuist_kit_acceptance_tests:
    name: TuistKit acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistKitAcceptanceTests
    triggering:
      <<: *branch_triggering
  tuist_app_tests:
    name: Tuist App tests
    max_build_duration: 60
    environment:
      xcode: 16.1
      groups:
        - tuist
        - github_credentials
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2024.11.8 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistApp -- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    triggering:
      <<: *branch_triggering
