environment:
  groups:
    - tuist

workflows:
  lint:
    name: Lint
    max_build_duration: 60
    environment:
      xcode: 15.2
    scripts:
      - name: Set environment variables
        script: | 
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | sh
          mise install
      - name: Lint
        script: mise run lint
    triggering: &branch_triggering
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true
  build_docs:
    name: Build Documentation
    max_build_duration: 60
    environment:
      xcode: 15.2
    scripts:
      - name: Set environment variables
        script: | 
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | sh
          mise install
      - name: Build
        script: bash ./make/tasks/github/build-docc.sh
    triggering:
      << : *branch_triggering
  deploy_docs:
    name: Deploy Documentation
    max_build_duration: 60
    environment:
      xcode: 15.2
    scripts:
      - name: Set environment variables
        script: | 
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=cc0237353f2f825680b0463629cd4a86"
      - name: Install Mise
        script: |
          curl https://mise.run | sh
          mise install
      - name: Lint
        script: bash ./make/tasks/github/build-docc.sh
      - name: Fix permissions
        script: sudo chown -R $USER .build/documentation
      - name: Deploy to Cloudflare Pages
        script: |
          mise install node@latest
          mise install npm:wrangler
          wrangler pages deploy --branch main --commit-hash $CM_COMMIT --branch $CM_BRANCH --project-name tuist-docs .build/documentation
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
      cancel_previous_builds: true