workflows:
  # FIXME: Merge all the schemes into one and remove all of the following workflows
  tuist_automation_acceptance_tests:
    name: Tuist automation acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.3
      groups:
        - tuist
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2025.1.5 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistAutomationAcceptanceTests
    triggering: &branch_triggering
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: true

  tuist_dependencies_acceptance_tests:
    name: Tuist dependencies acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.3
      groups:
        - tuist
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2025.1.5 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Set up new keychain
        script: |
          TMP_DIRECTORY=$(mktemp -d)
          KEYCHAIN_PATH=$TMP_DIRECTORY/keychain.keychain
          KEYCHAIN_PASSWORD=$(uuidgen)
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistDependenciesAcceptanceTests
    triggering:
      <<: *branch_triggering

  tuist_generator_acceptance_tests:
    name: Tuist generator acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.3
      groups:
        - tuist
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2025.1.5 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistGeneratorAcceptanceTests
    triggering:
      <<: *branch_triggering

  tuist_kit_acceptance_tests:
    name: TuistKit acceptance tests
    max_build_duration: 60
    environment:
      xcode: 16.3
      groups:
        - tuist
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.build
    scripts:
      - name: Set environment variables
        script: |
          echo "MISE_EXPERIMENTAL=1" >> $CM_ENV
      - name: Install Mise
        script: |
          curl https://mise.run | MISE_VERSION=v2025.1.5 sh
          mise install
      - name: Skip Xcode Macro Fingerprint Validation
        script: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Skip Xcode Package Validation
        script: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      - name: Install Tuist dependencies
        script: mise x -- tuist install
      - name: Run tests
        script: mise x -- tuist test TuistKitAcceptanceTests
    triggering:
      <<: *branch_triggering
