app = "tuist-cloud"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/app/bin/rails console"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"
  RAILS_PORT="3000"
  PHX_PORT="4000"
  RAILS_ENV="production"
  RAILS_MAX_THREADS=5
  WEB_CONCURRENCY=1

[[vm]]
  cpu_kind = 'shared'
  memory = "2048mb"
  cpus = 2

[processes]
  app = "/usr/local/bin/hivemind /app/Procfile"
  worker = "/app/bin/que"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["app"]
  http_options = { h2_backend = true }

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 60
    soft_limit = 50

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
