#!/usr/bin/env ruby
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require "pathname"

# Load Bundler dependencies
require "bundler/setup"

# Load fourier's directory
fourier_directory = File.expand_path("./projects/fourier/lib", __dir__)
$LOAD_PATH.unshift(fourier_directory) unless $LOAD_PATH.include?(fourier_directory)

# Load Fourier
require "fourier"

begin
  Fourier::CLI.start(ARGV)
rescue Fourier::Utilities::Errors::Error => error
  Fourier::Utilities::Output.error(error.message)
  Kernel.exit(1)
end
