# frozen_string_literal: true

source "https://rubygems.org"

gem "cucumber", "~> 3.1"
gem "rake", "~> 13.0"
gem "danger", "~> 6.0"
gem "byebug", "~> 11.0"
gem "minitest", "~> 5.12"
gem "simctl", "~> 1.6"
gem "rubocop", "~> 0.75.0"
gem "danger-rubocop"
gem "danger-swiftformat", "~> 0.6.0"
gem "danger-swiftlint", "~> 0.23.0"
gem "encrypted-environment", "~> 0.2.0"
gem "google-cloud-storage", "~> 1.21"
gem "colorize", "~> 0.8.1"
gem "cocoapods", "~> 1.8"
gem "xcodeproj", "~> 1.12"
gem "highline", "~> 2.0"
