global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":8080"

providers:
  file:
    directory: "./.traefik"
    watch: true

log:
  level: INFO

accessLog: {}

