#!/usr/bin/env bash
# mise description="Deploys the app to canary"

set -euo pipefail

flyctl deploy -c $MISE_PROJECT_ROOT/fly.canary.toml --dockerfile $MISE_PROJECT_ROOT/Dockerfile --build-arg TUIST_HOSTED=1 --build-arg MIX_ENV=can --vm-memory=2048 --wait-timeout 600
