#!/usr/bin/env bash
# mise description="Deploys the app to staging"

cd $MISE_PROJECT_ROOT && flyctl deploy -c $MISE_PROJECT_ROOT/fly.staging.toml --dockerfile $MISE_PROJECT_ROOT/Dockerfile --build-arg RAILS_ENV=staging --build-arg MIX_ENV=stag --vm-memory=2048 --wait-timeout 600
