#!/bin/sh

MAIN_APP_NAME="MainApp.app"
CLI_NAME="InnerCLI"

SOURCE_PATH="${TARGET_BUILD_DIR}/${CLI_NAME}"
TARGET_PATH="${TARGET_BUILD_DIR}/${MAIN_APP_NAME}/Contents/MacOS"

cp -r ${SOURCE_PATH} ${TARGET_PATH}
