inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails

Layout/LineLength:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - docs/**
    - website/**/*
