# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 2.7.0"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", ">= 1.4.4", require: false
gem "devise", "~> 4.8"
gem "dotenv-rails"
gem "jbuilder", "~> 2.7"
gem "js_from_routes", "~> 2.0"
gem "pg", "~> 1.1"
gem "puma", "~> 5.3.2"
gem "rails", "~> 6.1.4"
gem "redis", "~> 4.0"
gem "sass-rails", ">= 6"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "tailwindcss-rails", "~> 0.3.3"
gem "rolify", "~> 6.0"
gem "pundit", "~> 2.1"
gem "webpacker", "~> 5.4"
gem "actionpack-page_caching", "~> 1.2"
gem "front_matter_parser", "~> 1.0"
gem "redcarpet", "~> 3.5"
gem "rails_admin", "~> 2.1"
gem "sidekiq", "~> 6.2"
gem "bugsnag", "~> 6.21"
gem "dig_bang", "~> 0.2.1"
gem "octokit", "~> 4.21"
gem "securecompare", "~> 1.0"
gem "sidekiq-scheduler", "~> 3.1"
gem "react-rails", "~> 2.6"
gem "graphql", "~> 1.12"

# Omniauth
gem "omniauth", "~> 2.0"
gem "omniauth-github", "~> 2.0"
gem "omniauth-rails_csrf_protection", "~> 1.0"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "foreman", "~> 0.87.2"
  gem "listen", "~> 3.3"
  # gem "rack-mini-profiler", "~> 2.0"
  gem "spring"
  gem "web-console", ">= 4.1.0"
  gem "rubocop-shopify", require: false
  gem "rubocop-rails", "~> 2.10", require: false
  gem "graphql-schema_comparator", "~> 1.0"
end

group :test do
  gem "capybara", ">= 3.26"
  gem "mocha", "~> 1.12"
  gem "selenium-webdriver"
  gem "webdrivers"
end
gem "graphiql-rails", group: :development
