apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "atlas.webSelectorLabels" . | nindent 4 }}
