#!/usr/bin/env bash
# mise description="Encrypt the .env.json file in-place using SOPS with AGE encryption"

set -euo pipefail

sops encrypt -i --age "age1rjkec7xhu4tcesxsgvhm9px95zd0hj7l0zrl5m9saxeugfkm7v7s9aw65j" .env.json
