#!/usr/bin/env bash
# mise description="Devs the application"

set -eo pipefail

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

mix deps.get
pnpm install

if [ -z "$CI" ]; then
  $SCRIPT_DIR/db/reset
fi
