# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[bump]
initial_tag = "0.1.0"

[remote.github]
owner = "tuist"
repo = "swifterpm"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
## What's Changed{% if version %} in {{ version }}{% endif %}
<!-- RELEASE NOTES START -->
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
  {% if commit.remote.pr_title -%}
    {%- set commit_message = commit.remote.pr_title -%}
  {%- else -%}
    {%- set commit_message = commit.message -%}
  {%- endif -%}
  * {{ commit_message | split(pat="\n") | first | trim }}\
    {% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}){%- endif -%}
    {% if commit.remote.pr_number %} in \
      [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{% endfor %}

{% if version %}
  {% if previous.version %}
    **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
  {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = """
<!-- generated by git-cliff -->
"""
postprocessors = [
    { pattern = '\* (feat|fix|docs?|perf|refactor|style|test|chore|ci)(\([^)]*\))?:\s*', replace = "* " },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^refactor", group = "<!-- 2 -->Refactor" },
    { message = "^docs?", group = "<!-- 3 -->Documentation" },
    { message = "^test", group = "<!-- 4 -->Testing" },
    { message = "^perf", group = "<!-- 5 -->Performance" },
    { message = "^style", group = "<!-- 6 -->Styling" },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "^[0-9]+\\.[0-9]+\\.[0-9]+$"
skip_tags = "beta|alpha|rc"
sort_commits = "newest"
