# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", ">= 1.4.4", require: false
gem "jbuilder", "~> 2.7"
gem "pg", "~> 1.1"
gem "puma", "~> 5.3"
gem "rails", "~> 6.1.3"
gem "redis", "~> 4.0"
gem "sass-rails", ">= 6"
gem "sidekiq", "~> 6.2"
gem "turbolinks", "~> 5"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "devise", "~> 4.8"
gem "dotenv-rails"
gem "bugsnag", "~> 6.20"
gem "vite_rails", "~> 2.0.11"
gem "vite_plugin_legacy", "~> 0.5.5"
gem "js_from_routes", "~> 2.0"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "foreman", "~> 0.87.2"
  gem "listen", "~> 3.3"
  # gem "rack-mini-profiler", "~> 2.0"
  gem "spring"
  gem "web-console", ">= 4.1.0"
  gem "rubocop", "~> 1.14"
  gem "rubocop-rails", "~> 2.10.1"
  gem "rubocop-rails_config"
  gem "rubocop-shopify", "~> 2.1"
  gem "rubocop-rake", "~> 0.5.1"
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "mocha", "~> 1.12"
  gem "rubocop-minitest", "~> 0.12.1"
end
