# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"
require "graphql/rake_task"

GraphQL::RakeTask.new(schema_name: "TuistLabSchema")

desc("Starts Rails")
task start: :environment do
  system("bundle exec foreman start -f Procfile.dev") || abort
end

Rails.application.load_tasks
