# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

desc("Starts the Vite and Rails processes alongside")
task :start do
  system("bundle exec foreman start -f config/Procfile.dev") || abort
end

Rails.application.load_tasks
