Mimic.copy(Sentry)
Mimic.copy(SwiftRegistry.Config)
Mimic.copy(SwiftRegistry.Disk)
Mimic.copy(SwiftRegistry.Registry.Disk)
Mimic.copy(SwiftRegistry.CacheArtifacts)
Mimic.copy(ExAws.S3.Upload)
Mimic.copy(ExAws.S3)
Mimic.copy(ExAws)
Mimic.copy(ExAws.Config)
Mimic.copy(SwiftRegistry.S3)
Mimic.copy(SwiftRegistry.S3Transfers)
Mimic.copy(Plug.Conn)
Mimic.copy(Req)
Mimic.copy(OpenTelemetry.Tracer)
Mimic.copy(SwiftRegistry.Registry.Metadata)
Mimic.copy(SwiftRegistry.Registry.AlternateManifests)
Mimic.copy(TuistCommon.GitHub)
Mimic.copy(SwiftRegistry.Registry.Lock)
Mimic.copy(SwiftRegistry.Registry.SwiftPackageIndex)
Mimic.copy(SwiftRegistry.Registry.SyncCursor)
Mimic.copy(SwiftRegistry.CacheArtifactsBuffer)
Mimic.copy(SwiftRegistry.S3TransfersBuffer)
Mimic.copy(SwiftRegistry.Repo)
Mimic.copy(SwiftRegistry.AnalyticsCircuitBreaker)

ExUnit.start(max_cases: min(System.schedulers_online(), 4))
