# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[bump]
initial_tag = "0.1.0"

[remote.github]
owner = "tuist"
repo = "tuist"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
## What's Changed

{%- if version %} in {{ version }}{%- endif -%}
<!-- RELEASE NOTES START -->
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
  {% if commit.github.pr_title -%}
    {%- set commit_message = commit.github.pr_title -%}
  {%- else -%}
    {%- set commit_message = commit.message -%}
  {%- endif -%}
  * {{ commit_message | split(pat="\n") | first | trim }}\
    {% if commit.github.username %} by [@{{ commit.github.username }}](https://github.com/{{ commit.github.username }}){%- endif -%}
    {% if commit.github.pr_number %} in \
      [#{{ commit.github.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.github.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{% endfor %}

{% if version %}
    {% if previous.version %}
      **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
    {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
trim = true
footer = """
<!-- generated by git-cliff -->
"""
postprocessors = [
    { pattern = '\* (feat|fix|docs?|perf|refactor|style|test|chore|ci)(\([^)]*\))?:\s*', replace = "* " },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
commit_parsers = [
    { message = "^feat\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 0 -->⛰️  Features" },
    { message = "^fix\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^docs?\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 4 -->⚡ Performance" },
    { message = "^refactor\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^style\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test\\([^)]*\\bkura\\b[^)]*\\)", group = "<!-- 6 -->🧪 Testing" },
    { message = "^chore\\([^)]*\\bkura\\b[^)]*\\)", skip = true },
    { message = "^ci\\([^)]*\\bkura\\b[^)]*\\)", skip = true },
    { message = "^[a-z]+\\([^)]+\\)", skip = true },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "kura@[0-9].*"
skip_tags = "beta|alpha"
ignore_tags = "rc"
topo_order = false
sort_commits = "newest"
