secret_key_base: your-secret-key
smpt_settings:
  domain: your-smtp-domain
  user_name: your-smpt-username
  password: your-smpt-password
devise:
  secret_key: your-devise-secret-key
  pepper: your-devise-pepper
  omniauth:
    github:
      oauth_id: your-oauth-id
      oauth_secret: your-aouth-secrets
aws:
  access_key_id: your-aws-access-key
  secret_access_key: your-aws-secret-access-key
