base_urls: &base_urls
  app: http://127.0.0.1:3000
default: &default
  urls:
    <<: *base_urls
  smpt_settings:
    authentication: plain
    address: smtp.mailgun.org
    port: 587
  blocklisted_slug_keywords:
    - new
    - project
    - projects
    - settings
    - organizations
    - organization
development: &development
  <<: *default
production:
  <<: *default
  urls:
    <<: *base_urls
    app: https://cloud.tuist.io
  smpt_settings:
    authentication: plain
    address: smtp.eu.mailgun.org
    port: 587
  domain: cloud.tuist.io
test:
  <<: *development
