#!/usr/bin/env bash
# mise description="Run Tuist commands using SPM-built binary with custom arguments"

set -eo pipefail

swift build --package-path $MISE_PROJECT_ROOT
$MISE_PROJECT_ROOT/.build/debug/tuist $@
