# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "rails", "~> 7.0"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 5.0"
gem "sass-rails", ">= 6"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder", "~> 2.7"
gem "bootsnap", ">= 1.4.2", require: false
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "google-cloud-bigquery", "~> 1.24"
gem "chartkick", "~> 3.4"
gem "groupdate", "~> 5.2"
gem "slack-ruby-client", "~> 0.17.0"
gem "sidekiq-scheduler", "~> 3.1"
gem "slack-ruby-block-kit", "~> 0.17.0"
gem "bugsnag", "~> 6.24"
gem "importmap-rails"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rubocop-minitest", "~> 0.16.0"
  gem "rubocop-shopify", "~> 1.0"
end

group :development do
  gem "web-console", ">= 3.3.0"
  gem "listen", "~> 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "rubocop", "~> 0.93.0"
  gem "rubocop-rails", "~> 2.8.1"
  gem "rubocop-rails_config"
  gem "foreman", "~> 0.87.2"
  gem "brakeman", "~> 4.10"
end

group :test do
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  gem "webdrivers"
end
