default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
development: &development
  <<: *default
  database: galaxy_development
test:
  <<: *development
  database: galaxy_test
production:
  <<: *default
  url: <%= (Rails.env.production?)? ENV.fetch("DATABASE_URL") : "" %>