http:
  routers:
    phx:
      rule: "Path(`/api-docs`) || Path(`/api/openapi`) || Path(`/api/cache`) || Path(`/api/cache/exists`) || Path(`/api/cache/multipart/generate-url`) || Path(`/api/cache/multipart/start`) || Path(`/api/cache/multipart/complete`)"
      service: phx

  services:
    phx:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1:4000/"
        passHostHeader: true
