Mimic.copy(Atlas.Accounts.ExchangeRates, type_check: true)
Mimic.copy(Atlas.Accounts, type_check: true)
Mimic.copy(Atlas.Finance, type_check: true)
Mimic.copy(Atlas.Finance.Briefs.Adapter, type_check: true)
Mimic.copy(Atlas.Finance.Config, type_check: true)
Mimic.copy(Atlas.Finance.Agents.CostDigestAgent, type_check: true)
Mimic.copy(Atlas.Finance.CostDigestNotifier, type_check: true)
Mimic.copy(Atlas.Finance.Agents.PaymentDetectionAgent, type_check: true)
Mimic.copy(Atlas.Finance.PaymentCelebrationNotifier, type_check: true)
Mimic.copy(Atlas.Finance.PaymentDetection, type_check: true)
Mimic.copy(Atlas.Finance.Agents.WeeklySummaryAgent, type_check: true)
Mimic.copy(Atlas.Finance.WeeklySummaryNotifier, type_check: true)
Mimic.copy(Atlas.Finance.Providers.Mercury, type_check: true)
Mimic.copy(Atlas.Finance.Providers.Qonto, type_check: true)
Mimic.copy(Atlas.LLMs, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.OverviewSummaryAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.OutcomeProposalAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.ScreenshotNoteAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.EmailEventAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.GranolaMeetingAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.ServiceLevelExtractionAgent, type_check: true)
Mimic.copy(Atlas.Accounts.Agents.InvoicePaidCelebrationAgent, type_check: true)
Mimic.copy(Atlas.Accounts.InvoicePaidNotifier, type_check: true)
Mimic.copy(Atlas.Granola.API, type_check: true)
Mimic.copy(Atlas.Integrations.GitHubAPI, type_check: true)
Mimic.copy(Atlas.Environment, type_check: true)
Mimic.copy(Atlas.Users, type_check: true)
Mimic.copy(Atlas.MCP)
Mimic.copy(Atlas.MCP.Proxy, type_check: true)
Mimic.copy(Atlas.MCP.Proxy.Config, type_check: true)
Mimic.copy(Atlas.Browser, type_check: true)
Mimic.copy(Atlas.MCP.Tools.SearchWeb, type_check: true)
Mimic.copy(Atlas.Briefs.Config, type_check: true)
Mimic.copy(Atlas.Slack.API, type_check: true)
Mimic.copy(Atlas.FeatureUsage.Collector, type_check: true)
Mimic.copy(Atlas.TuistOverview, type_check: true)
Mimic.copy(Atlas.FeatureUsage.UsageNotifier, type_check: true)
Mimic.copy(Atlas.Slack.AgentConfig, type_check: true)
Mimic.copy(Atlas.Slack.Bot, type_check: true)
Mimic.copy(Atlas.Slack.Installations, type_check: true)
Mimic.copy(Atlas.Slack.ConversationResponder, type_check: true)
Mimic.copy(Atlas.Slack.URLContent, type_check: true)
Mimic.copy(Atlas.LLMs.Runner, type_check: true)
Mimic.copy(Atlas.Slack.Workers.RespondToConversation, type_check: true)
Mimic.copy(Atlas.Slack, type_check: true)
Mimic.copy(Atlas.GTM, type_check: true)
Mimic.copy(Atlas.Contracts.Storage, type_check: true)
Mimic.copy(Atlas.UUIDv7, type_check: true)
Mimic.copy(Atlas.Mailer, type_check: true)
Mimic.copy(AtlasWeb.SubscriptionRateLimit, type_check: true)
Mimic.copy(AtlasWeb.SupportChatRateLimit, type_check: true)
Mimic.copy(Atlas.GTM.BlogPostIdeaNotifier, type_check: true)
Mimic.copy(Atlas.GTM.AudienceMemberNotifier, type_check: true)
Mimic.copy(Atlas.GTM.Outreach.Apollo, type_check: true)
Mimic.copy(Atlas.Outreach.CandidateNotifier, type_check: true)
Mimic.copy(Atlas.Outreach.Agents.RecommendationAgent, type_check: true)
Mimic.copy(Atlas.Outreach.RecommendationNotifier, type_check: true)
Mimic.copy(Atlas.Stripe, type_check: true)
Mimic.copy(Atlas.Licenses.Config, type_check: true)
Mimic.copy(Atlas.Licenses.ExpirationNotifier, type_check: true)
Mimic.copy(Atlas.Licenses.RateLimiter, type_check: true)
Mimic.copy(Atlas.Letters.Config, type_check: true)
Mimic.copy(Atlas.Letters, type_check: true)
Mimic.copy(Atlas.Letters.Pingen, type_check: true)
Mimic.copy(Atlas.Inbox.Dkim, type_check: true)
Mimic.copy(Atlas.Inbox.Dkim.Resolver, type_check: true)
Mimic.copy(Atlas.Vector)
Mimic.copy(Atlas.Memory.BulletinSynthesizer, type_check: true)
Mimic.copy(Atlas.Memory.EdgeClassifier, type_check: true)
Mimic.copy(Req)
Mimic.copy(Oban)
Mimic.copy(Condukt, type_check: true)
Mimic.copy(Atlas.IngestRepo)
Mimic.copy(Atlas.Engineering.Errors, type_check: true)
Mimic.copy(Atlas.Engineering.Errors.Availability, type_check: true)
Mimic.copy(Atlas.Engineering.Errors.Event.Buffer, type_check: true)
Mimic.copy(Atlas.Engineering.Errors.IssueCoalescer, type_check: true)
Mimic.copy(Atlas.Engineering.Errors.DropAlerter, type_check: true)
Mimic.copy(Atlas.Engineering.Errors.Summaries, type_check: true)
Mimic.copy(Atlas.ObjectStorage, type_check: true)

# The suite runs every module concurrently, so a process that is merely slow to
# be scheduled must not read as a process that never sent its message. This only
# affects how long a failing assertion waits; a passing one returns immediately.
# `refute_receive` keeps the tighter default, since waiting longer there costs
# real time on every run.
ExUnit.start(assert_receive_timeout: 1_000)
Ecto.Adapters.SQL.Sandbox.mode(Atlas.Repo, :manual)
