# frozen_string_literal: true

source('https://rubygems.org')
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby('2.6.3')

gem('rails', '~> 6.0.0')
gem('pg', '>= 0.18', '< 2.0')
gem('puma', '~> 4.2')
gem('sass-rails', '~> 6.0')
gem('uglifier', '>= 1.3.0')
gem('coffee-rails', '~> 5.0')
gem('jbuilder', '~> 2.5')
gem('bootsnap', '>= 1.1.0', require: false)
gem('tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby])
gem("sentry-raven")
gem("sidekiq", "~> 6.0")
gem('webpacker', '~> 4.x')

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "foreman", "~> 0.86.0"
  gem 'brakeman'
  gem 'prettier'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'erb_lint'
end
