server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: .+
        action: keep
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_kura_region]
        target_label: region
      - source_labels: [__meta_docker_container_label_kura_tenant_id]
        target_label: tenant_id
