//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconCluster) DeepCopyInto(out *ScalewayAppleSiliconCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconCluster.
func (in *ScalewayAppleSiliconCluster) DeepCopy() *ScalewayAppleSiliconCluster {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconClusterList) DeepCopyInto(out *ScalewayAppleSiliconClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalewayAppleSiliconCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconClusterList.
func (in *ScalewayAppleSiliconClusterList) DeepCopy() *ScalewayAppleSiliconClusterList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconClusterSpec) DeepCopyInto(out *ScalewayAppleSiliconClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconClusterSpec.
func (in *ScalewayAppleSiliconClusterSpec) DeepCopy() *ScalewayAppleSiliconClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconClusterStatus) DeepCopyInto(out *ScalewayAppleSiliconClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconClusterStatus.
func (in *ScalewayAppleSiliconClusterStatus) DeepCopy() *ScalewayAppleSiliconClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachine) DeepCopyInto(out *ScalewayAppleSiliconMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachine.
func (in *ScalewayAppleSiliconMachine) DeepCopy() *ScalewayAppleSiliconMachine {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineList) DeepCopyInto(out *ScalewayAppleSiliconMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalewayAppleSiliconMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineList.
func (in *ScalewayAppleSiliconMachineList) DeepCopy() *ScalewayAppleSiliconMachineList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineSpec) DeepCopyInto(out *ScalewayAppleSiliconMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineSpec.
func (in *ScalewayAppleSiliconMachineSpec) DeepCopy() *ScalewayAppleSiliconMachineSpec {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineStatus) DeepCopyInto(out *ScalewayAppleSiliconMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineStatus.
func (in *ScalewayAppleSiliconMachineStatus) DeepCopy() *ScalewayAppleSiliconMachineStatus {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineTemplate) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineTemplate.
func (in *ScalewayAppleSiliconMachineTemplate) DeepCopy() *ScalewayAppleSiliconMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalewayAppleSiliconMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineTemplateList.
func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopy() *ScalewayAppleSiliconMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineTemplateResource) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineTemplateResource.
func (in *ScalewayAppleSiliconMachineTemplateResource) DeepCopy() *ScalewayAppleSiliconMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalewayAppleSiliconMachineTemplateSpec) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalewayAppleSiliconMachineTemplateSpec.
func (in *ScalewayAppleSiliconMachineTemplateSpec) DeepCopy() *ScalewayAppleSiliconMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
