//go:build !ignore_autogenerated

// Hand-written DeepCopy methods. We don't run controller-gen in the
// repo (no scaffolded Kubebuilder project), so we maintain these by
// hand. Keep in sync with the type definitions above.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// === ScalewayAppleSiliconMachine ============================================

func (in *ScalewayAppleSiliconMachine) DeepCopyInto(out *ScalewayAppleSiliconMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ScalewayAppleSiliconMachine) DeepCopy() *ScalewayAppleSiliconMachine {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachine)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconMachineList) DeepCopyInto(out *ScalewayAppleSiliconMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ScalewayAppleSiliconMachine, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ScalewayAppleSiliconMachineList) DeepCopy() *ScalewayAppleSiliconMachineList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineList)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconMachineSpec) DeepCopyInto(out *ScalewayAppleSiliconMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		out.ProviderID = new(string)
		*out.ProviderID = *in.ProviderID
	}
}

func (in *ScalewayAppleSiliconMachineStatus) DeepCopyInto(out *ScalewayAppleSiliconMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		out.Addresses = make([]clusterv1.MachineAddress, len(in.Addresses))
		copy(out.Addresses, in.Addresses)
	}
	if in.FailureReason != nil {
		out.FailureReason = new(string)
		*out.FailureReason = *in.FailureReason
	}
	if in.FailureMessage != nil {
		out.FailureMessage = new(string)
		*out.FailureMessage = *in.FailureMessage
	}
	if in.Conditions != nil {
		out.Conditions = make(clusterv1.Conditions, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// === ScalewayAppleSiliconMachineTemplate ====================================

func (in *ScalewayAppleSiliconMachineTemplate) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *ScalewayAppleSiliconMachineTemplate) DeepCopy() *ScalewayAppleSiliconMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ScalewayAppleSiliconMachineTemplate, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopy() *ScalewayAppleSiliconMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconMachineTemplateSpec) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *ScalewayAppleSiliconMachineTemplateResource) DeepCopyInto(out *ScalewayAppleSiliconMachineTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// === ScalewayAppleSiliconCluster ============================================

func (in *ScalewayAppleSiliconCluster) DeepCopyInto(out *ScalewayAppleSiliconCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ScalewayAppleSiliconCluster) DeepCopy() *ScalewayAppleSiliconCluster {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconClusterList) DeepCopyInto(out *ScalewayAppleSiliconClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ScalewayAppleSiliconCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ScalewayAppleSiliconClusterList) DeepCopy() *ScalewayAppleSiliconClusterList {
	if in == nil {
		return nil
	}
	out := new(ScalewayAppleSiliconClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *ScalewayAppleSiliconClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ScalewayAppleSiliconClusterStatus) DeepCopyInto(out *ScalewayAppleSiliconClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make(clusterv1.Conditions, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
