apiVersion: v1
kind: Service
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "alloy.selectorLabels" . | nindent 4 }}
  ports:
    - name: loki
      port: {{ .Values.ports.loki }}
      targetPort: loki
    - name: otlp
      port: {{ .Values.ports.otlp }}
      targetPort: otlp
      protocol: TCP
    - name: ui
      port: {{ .Values.ports.ui }}
      targetPort: ui
