#!/usr/bin/env bash
# mise description="Lint the workspace using SwiftFormat, SwiftLint, and Tuist implicit imports analysis"

set -euo pipefail

swiftformat cli/ app/ --lint
swiftlint lint --quiet --config .swiftlint.yml cli/Sources
tuist inspect implicit-imports
