name = "tuist-worker-production"
main = "src/index.js"
compatibility_date = "2025-01-08"
routes = [
  "https://tuist.dev/api/cas/*"
]

[[kv_namespaces]]
binding = "CAS_CACHE"
id = "2adf75e070fd43cabee0be83cb4a562d"
preview_id = "2f1058911a144cab9c8816478e03f4e2"

[dev]
port = 8787

# Development environment
[env.development]
name = "tuist-worker-development"
[[env.development.kv_namespaces]]
binding = "CAS_CACHE"
id = "2f1058911a144cab9c8816478e03f4e2"

# Staging environment
[env.staging]
name = "tuist-worker-staging"
routes = [
  "https://staging.tuist.dev/api/cas/*"
]
[[env.staging.kv_namespaces]]
binding = "CAS_CACHE"
id = "4eecec1f40f84dc1bd8233944b835934"

# Canary environment
[env.canary]
name = "tuist-worker-canary"
routes = [
  "https://canary.tuist.dev/api/cas/*"
]
[[env.canary.kv_namespaces]]
binding = "CAS_CACHE"
id = "c95cdd9d54fa49b89465b3993c298186"
