#!/usr/bin/env bash

bundle install
npm install

if [ ! -f config/master.key ]; then
  echo "Input data for development credentials – use config/credentials.example.yml as an example. For development, you can keep the mock data from the example yml."
  EDITOR="code --wait" bin/rails credentials:edit
fi
