defmodule Atlas.GTM.Delivery do
  use Atlas.Schema

  import Ecto.Changeset

  alias Atlas.GTM.Audience
  alias Atlas.GTM.Broadcast
  alias Atlas.GTM.Subscriber

  @kinds ~w(broadcast welcome confirmation transactional)
  @statuses ~w(pending delivered failed skipped)

  schema "gtm_deliveries" do
    field :kind, :string
    field :recipient_email, :string
    field :recipient_name, :string
    field :subject, :string
    field :status, :string, default: "pending"
    field :provider_message_id, :string
    field :error, :string
    field :attempts, :integer, default: 0
    field :metadata, :map, default: %{}
    field :delivered_at, :utc_datetime

    belongs_to :broadcast, Broadcast
    belongs_to :audience, Audience
    belongs_to :subscriber, Subscriber

    timestamps()
  end

  def kinds, do: @kinds
  def statuses, do: @statuses

  def changeset(delivery, attrs) do
    delivery
    |> cast(attrs, [
      :kind,
      :recipient_email,
      :recipient_name,
      :subject,
      :status,
      :provider_message_id,
      :error,
      :attempts,
      :metadata,
      :delivered_at
    ])
    |> validate_required([:kind, :recipient_email, :subject, :status])
    |> validate_inclusion(:kind, @kinds)
    |> validate_inclusion(:status, @statuses)
    # UUID primary keys are generated by the application. Map the exceedingly
    # rare collision to a changeset error so callers can safely retry it with a
    # new generated value instead of letting the database exception escape.
    |> unique_constraint(:id, name: :gtm_deliveries_pkey)
    |> unique_constraint([:broadcast_id, :recipient_email])
    |> unique_constraint([:subscriber_id, :kind], name: :gtm_deliveries_unique_welcome_index)
    |> foreign_key_constraint(:broadcast_id)
    |> foreign_key_constraint(:audience_id)
    |> foreign_key_constraint(:subscriber_id)
  end
end
