#!/usr/bin/env bash
#
# Zero-touch provisioning for a rack switch, on an isolated segment.
#
# A factory switch with Auto Install enabled boots, asks DHCP for an address and
# a boot file, fetches that file over TFTP and applies it. This serves both
# halves: dnsmasq for DHCP and TFTP, and the configuration rendered from the
# site definition.
#
# The dangerous part is not the switch, it is the DHCP server. A second DHCP
# server on a network people live on hands out addresses to laptops and phones,
# so this refuses to run on the interface carrying the default route and binds
# to exactly one interface. Use a USB Ethernet adapter with the switch on the
# other end and nothing else attached.
#
#   mise run rack:ztp <device> --interface en5 [--dry-run]
#
# See infra/rack-switch-fleet/AGENTS.md.

set -euo pipefail

FLEET_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source-path=SCRIPTDIR
source "$FLEET_ROOT/lib/config.sh"

SITE="${RACK_SITE:-ber1}"
device=""
interface=""
dry_run=0

while (( $# )); do
  case "$1" in
    --interface) interface="${2:-}"; shift 2;;
    --site) SITE="${2:-}"; shift 2;;
    --dry-run) dry_run=1; shift;;
    -*) echo "unknown flag: $1" >&2; exit 2;;
    *) device="$1"; shift;;
  esac
done

site_file="$(fleet_site_file "$SITE")"
[ -f "$site_file" ] || { echo "error: no site definition at $site_file" >&2; exit 2; }
[ -n "$device" ] || { echo "usage: mise run rack:ztp <device> --interface <iface> [--dry-run]" >&2; exit 2; }
[ -n "$interface" ] || {
  echo "error: --interface is required, and it must be an isolated segment." >&2
  echo "       Use a USB Ethernet adapter with only the switch on it. This serves DHCP," >&2
  echo "       and a second DHCP server on a network with people on it hands addresses" >&2
  echo "       to their laptops." >&2
  exit 2
}

entry="$(fleet_device "$site_file" "$device")"
mac="$(jq -r '.mac // empty' <<<"$entry")"
credential_item="$(jq -r '.credential_item' <<<"$entry")"
vault="$(jq -r '.credentials.vault' "$site_file")"

# --- refuse to become a rogue DHCP server ------------------------------------

default_interface="$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')"
if [ "$interface" = "$default_interface" ]; then
  echo "error: $interface carries this machine's default route, so it is the network you" >&2
  echo "       are on. Serving DHCP there would hand addresses to everything on it." >&2
  exit 1
fi
if ! ifconfig "$interface" >/dev/null 2>&1; then
  echo "error: no interface $interface" >&2
  exit 1
fi
server_ip="$(ipconfig getifaddr "$interface" 2>/dev/null || true)"
if [ -z "$server_ip" ]; then
  echo "error: $interface has no IPv4 address, so there is nothing to serve from." >&2
  echo "       Give it one on the isolated segment first, for example:" >&2
  echo "         sudo ifconfig $interface inet 192.168.50.1 netmask 255.255.255.0 up" >&2
  exit 1
fi

# --- the configuration the switch will fetch ---------------------------------
#
# A factory switch has none of our credentials, so unlike `replace`, which
# carries the login across from the switch itself, this has to put one in. The
# hash cannot be computed here, so it is stored in the switch's 1Password item
# alongside the password it belongs to.

boot_file="$device.cfg"
tftp_root="$(mktemp -d)"
rendered="$(mktemp)"
fleet_render "$site_file" "$device" > "$rendered"

secret=""
if op_args=(item get "$credential_item" --vault "$vault" --format=json) && \
   credentials="$(op "${op_args[@]}" 2>/dev/null)"; then
  secret="$(jq -r '.fields[]? | select(.label == "config-hash") | .value // empty' <<<"$credentials")"
fi
if [ -z "$secret" ]; then
  echo "error: no 'config-hash' field on the 1Password item '$credential_item'." >&2
  echo "" >&2
  echo "       A switch being provisioned from scratch has none of our credentials, so the" >&2
  echo "       config it fetches has to contain the login. The hash cannot be computed" >&2
  echo "       here; take it from a switch that is already prepped, where" >&2
  echo "       'copy startup-config tftp' writes a line of the form:" >&2
  echo "         user name tuist privilege admin secret 5 <hash>" >&2
  echo "       and add that <hash> to the item as a field named config-hash." >&2
  rm -rf "$tftp_root" "$rendered"
  exit 1
fi

username="$(jq -r '.credentials.username' "$site_file")"
served="$tftp_root/$boot_file"
{
  # ahead of `telnet disable`, which is where a prepped switch keeps it
  awk -v line="user name $username privilege admin secret 5 $secret" '
    $0 ~ /^telnet / && !done { print line; done = 1 } { print }' "$rendered"
} | fleet_device_file > "$served"

# --- dnsmasq: DHCP and TFTP, and deliberately no DNS -------------------------

conf="$tftp_root/dnsmasq.conf"
subnet="${server_ip%.*}"
{
  echo "# generated by rack:ztp, do not edit"
  echo "port=0"                      # no DNS at all
  echo "interface=$interface"
  echo "bind-interfaces"
  echo "except-interface=lo0"
  echo "no-hosts"
  echo "no-resolv"
  echo "dhcp-authoritative"
  echo "dhcp-range=$subnet.100,$subnet.150,1h"
  echo "enable-tftp"
  echo "tftp-root=$tftp_root"
  echo "dhcp-option=66,\"$server_ip\""
  echo "log-dhcp"
  if [ -n "$mac" ]; then
    echo "dhcp-host=$mac,set:$device"
    echo "dhcp-option=tag:$device,67,\"$boot_file\""
  else
    echo "# no mac in the site definition, so every client is offered this file"
    echo "dhcp-boot=$boot_file"
  fi
} > "$conf"

echo "interface     $interface at $server_ip (default route is on ${default_interface:-none})"
echo "serving       $boot_file from $tftp_root"
echo "to            ${mac:-any client on this segment}"
echo ""
echo "dnsmasq configuration:"
sed 's/^/  /' "$conf"
echo ""
echo "the switch would fetch (login line redacted):"
tr -d '\000' < "$served" | tr -d '\r' | sed "s/secret 5 .*/secret 5 <redacted>/" | head -20 | sed 's/^/  /'
echo "  ... $(tr -d '\000' < "$served" | grep -c '' ) lines"

if (( dry_run )); then
  echo ""
  echo "dry run, nothing served. The files are in $tftp_root"
  exit 0
fi

command -v dnsmasq >/dev/null 2>&1 || {
  echo "error: dnsmasq is not installed (brew install dnsmasq)" >&2
  rm -rf "$tftp_root" "$rendered"
  exit 1
}

echo ""
echo "This serves DHCP on $interface. Confirm nothing but the switch is on that segment."
if [ -t 0 ]; then
  read -r -p "start? [y/N] " answer
  [ "$answer" = "y" ] || [ "$answer" = "Y" ] || { rm -rf "$tftp_root" "$rendered"; exit 130; }
fi

echo "serving; power the switch on with Auto Install armed. Ctrl-C to stop."
trap 'echo ""; echo "stopped. Files were in $tftp_root"; rm -f "$rendered"' EXIT
sudo dnsmasq --conf-file="$conf" --no-daemon --log-facility=-
