# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionView::Helpers::FormTagHelper`.
# Please instead update this file by running `bin/tapioca dsl ActionView::Helpers::FormTagHelper`.

module ActionView::Helpers::FormTagHelper
  mixes_in_class_methods ::ActionView::Helpers::UrlHelper::ClassMethods
  mixes_in_class_methods ::ActionView::Helpers::SanitizeHelper::ClassMethods
end
