defmodule Tuist.Webhooks.DeliveryAttempt do
  @moduledoc """
  One HTTP attempt at delivering a webhook event to an endpoint, stored
  in ClickHouse (`webhook_delivery_attempts`).

  An event delivered via `Tuist.Webhooks.Workers.DeliveryWorker` produces
  one row per HTTP call — the initial send and each retry — capturing
  what we sent and what came back so the dashboard can show the request
  body, response headers, and error inline.

  The `status` field collapses each row to either `"delivered"` (2xx) or
  `"failed"` (non-2xx, transport error, SSRF reject). Higher-level
  lifecycle states like "pending" or "retrying" live on the Oban job,
  not on individual attempts.

  See `Tuist.IngestRepo.Migrations.CreateWebhookDeliveryAttemptsTable`
  for the engine / partition / TTL rationale.

  Writes go through the per-schema `Buffer` generated by
  `Tuist.Ingestion.Bufferable` — a delivery batch from one test
  ingestion can produce hundreds of attempts in a tight window, and
  individual `IngestRepo.insert_all` calls would create one CH part
  per row.
  """
  use Ecto.Schema
  use Tuist.Ingestion.Bufferable

  # Flop drives cursor pagination on the per-endpoint deliveries table.
  # Only `inserted_at` needs to be sortable — the table is always shown
  # newest-first, and the microsecond resolution of `DateTime64(6)` is
  # unique enough in practice. No filters go through Flop; the context
  # composes them onto the queryable directly so the CH-native
  # `positionCaseInsensitive` substring search stays available.
  @derive {
    Flop.Schema,
    filterable: [],
    sortable: [:inserted_at],
    default_pagination_type: :first,
    default_order: %{order_by: [:inserted_at], order_directions: [:desc]}
  }

  @primary_key {:id, Ch, type: "UUID", autogenerate: false}
  schema "webhook_delivery_attempts" do
    field :webhook_endpoint_id, Ch, type: "UUID"
    field :event_id, Ch, type: "String"
    field :event_type, Ch, type: "LowCardinality(String)"
    field :attempt, Ch, type: "UInt8"
    field :status, Ch, type: "LowCardinality(String)"
    field :request_body, Ch, type: "String", default: ""
    # Headers are stored JSON-encoded; the dashboard decodes once per
    # render. Using CH's `Map` would force a stricter type contract for
    # values we treat as opaque strings.
    field :request_headers, Ch, type: "String", default: ""
    # `0` is the sentinel for "no HTTP response received" (network
    # error, SSRF reject, timeout). The dashboard checks `> 0` before
    # rendering the response code.
    field :response_status, Ch, type: "UInt16", default: 0
    field :response_headers, Ch, type: "String", default: ""
    field :response_body, Ch, type: "String", default: ""
    field :error, Ch, type: "String", default: ""
    field :duration_ms, Ch, type: "UInt32", default: 0
    field :inserted_at, Ch, type: "DateTime64(6, 'UTC')"
  end
end
