#!/bin/bash

set -e

shell_join() {
  local arg
  printf "%s" "$1"
  shift
  for arg in "$@"; do
    printf " "
    printf "%s" "${arg// /\ }"
  done
}

ohai() {
  printf "${tty_blue}==>${tty_bold} %s${tty_reset}\n" "$(shell_join "$@")"
}

warn() {
  printf "${tty_red}Warning${tty_reset}: %s\n" "$(chomp "$1")"
}

LATEST_VERSION=$(curl --silent "https://api.github.com/repos/tuist/tuist/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

ohai "Downloading tuistenv..."
curl -LSs --output /tmp/tuistenv.zip https://github.com/tuist/tuist/releases/download/${LATEST_VERSION}/tuistenv.zip
ohai "Unzipping tuistenv..."
unzip -o /tmp/tuistenv.zip -d /tmp/tuistenv > /dev/null
ohai "Installing tuistenv..."

if [[ ! -d "/usr/local/bin" ]]; then
  mkdir -p /usr/local/bin/
fi

if [[ -f "/usr/local/bin/tuist" ]]; then
  rm /usr/local/bin/tuist
fi

mv /tmp/tuistenv/tuistenv /usr/local/bin/tuist
chmod +x /usr/local/bin/tuist

rm -rf /tmp/tuistenv
rm /tmp/tuistenv.zip

ohai "tuistenv installed. Try running 'tuist'"
ohai "Check out the documentation at https://docs.tuist.io/"
