openapi: "3.0.3"
info:
  title: Tuist Cloud API
  version: 0.1.0
servers:
  - url: http://127.0.0.1:3000/api
    description: Localhost deployment.
paths:
  /api/projects:
    post:
      operationId: createProject
      parameters:
        - name: name
          required: true
          in: query
          description: The name of the project that should be created.
          schema:
            type: string
        - name: organization
          required: false
          in: query
          description: Organization to create the project with. If nil, the project will be created with the current user's personal account.
          schema:
            type: string
      responses:
        "200":
          description: A success response with the created project.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "400":
          description: The project could not be created because of a validation error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: number
        slug:
          type: string
      required:
        - id
        - slug
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message