#!/usr/bin/env bash
# mise description="Generate Swift client code from OpenAPI specification for TuistServer integration"

set -euo pipefail

swift-openapi-generator generate --mode types --mode client --output-directory $MISE_PROJECT_ROOT/cli/Sources/TuistServer/OpenAPI $MISE_PROJECT_ROOT/cli/Sources/TuistServer/OpenAPI/server.yml
