{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "noora-storybook.fullname" . }}
  labels:
    {{- include "noora-storybook.labels" . | nindent 4 }}
    app.kubernetes.io/component: storybook
spec:
  podSelector:
    matchLabels:
      {{- include "noora-storybook.componentLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressControllerNamespace | quote }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressControllerPodLabels | nindent 14 }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dnsNamespace | quote }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
