/// A target of a project.
public struct Target: Codable, Equatable, Sendable {
    /// The name of the target. Also, the product name if not specified with ``productName``.
    public var name: String

    /// The destinations this target supports, e.g. iPhone, appleVision, macCatalyst
    public var destinations: Destinations

    /// The type of build product this target will output.
    public var product: Product

    /// The built product name. If nil, it will be equal to ``name``.
    public var productName: String?

    /// The product bundle identifier.
    public var bundleId: String

    /// The minimum deployment targets your product will support.
    public var deploymentTargets: DeploymentTargets?

    /// The Info.plist representation.
    public var infoPlist: InfoPlist?

    /// The source files of the target.
    /// Note: any playgrounds matched by the globs used in this property will be automatically added.
    public var sources: SourceFilesList?

    /// The resource files of target.
    /// Note: localizable files, `*.lproj`, are supported.
    public var resources: ResourceFileElements?

    /// The build phase copy files actions for the target.
    public var copyFiles: [CopyFilesAction]?

    /// The headers for the target.
    public var headers: Headers?

    /// The entitlements representation.
    ///
    /// > Note: For per-configuration entitlements, you should:
    /// > 1. Keep this property as `nil`
    /// > 2. Set the `CODE_SIGN_ENTITLEMENTS` build setting using `Target.settings` for each configuration
    /// > 3. If you want the entitlement files to be included in the project navigator, add them using `Project.additionalFiles`
    /// >
    /// > Example:
    /// > ```swift
    /// > let target = Target(
    /// >     name: "MyApp",
    /// >     // ... other properties
    /// >     entitlements: nil, // Important: keep this as nil
    /// >     settings: .settings(
    /// >         configurations: [
    /// >             .debug(name: "Debug", settings: ["CODE_SIGN_ENTITLEMENTS": "Debug.entitlements"]),
    /// >             .release(name: "Release", settings: ["CODE_SIGN_ENTITLEMENTS": "Release.entitlements"])
    /// >         ]
    /// >     )
    /// > )
    /// >
    /// > let project = Project(
    /// >     name: "MyProject",
    /// >     targets: [target],
    /// >     additionalFiles: [
    /// >         "Debug.entitlements",
    /// >         "Release.entitlements"
    /// >     ]
    /// > )
    /// > ```
    public var entitlements: Entitlements?

    /// The build phase scripts actions for the target.
    public var scripts: [TargetScript]

    /// The target's dependencies.
    public var dependencies: [TargetDependency]

    /// The target's settings.
    public var settings: Settings?

    /// The Core Data models.
    public var coreDataModels: [CoreDataModel]

    /// The environment variables. Used by autogenerated schemes for the target.
    public var environmentVariables: [String: EnvironmentVariable]

    /// The launch arguments. Used by autogenerated schemes for the target.
    public var launchArguments: [LaunchArgument]

    /// The additional files for the target. For project's additional files, see ``Project/additionalFiles``.
    public var additionalFiles: [FileElement]

    /// The build rules used for transformation of source files during compilation.
    public var buildRules: [BuildRule]

    /// Specifies whether if the target can merge or not the dynamic dependencies as part of its binary
    public var mergedBinaryType: MergedBinaryType

    /// Specifies whether if the target can be merged as part of another binary or not
    public var mergeable: Bool

    /// The target's tags associated with on demand resources
    public var onDemandResourcesTags: OnDemandResourcesTags?

    /// The target's metadata.
    public var metadata: TargetMetadata

    /// The target's buildable folders.
    public var buildableFolders: [BuildableFolder]

    /// Properties for a foreign build target. Set when this target was created with
    /// ``foreignBuild(name:destinations:script:inputs:output:metadata:)`` or
    /// ``kotlinMultiplatform(name:destinations:gradleProject:frameworkName:linking:compileKotlinFrameworkScript:compileKotlinXCFrameworkScript:xcframeworkPath:inputs:metadata:)``.
    public private(set) var foreignBuild: ForeignBuild?

    /// Describes the properties of a foreign (non-Xcode) build target.
    ///
    /// A foreign build can declare two XCFramework builds: a `xcframework` build that produces the
    /// universal artifact (all slices, used when warming the binary cache) and an optional
    /// `developmentXCFramework` build that produces a thinner artifact for the current destination
    /// (used during regular generation, so local iteration doesn't pay for the full build). Both are
    /// XCFrameworks, so they link and embed through the same wiring; Tuist just picks which to build
    /// per context. Generic foreign builds leave `developmentXCFramework` unset and always build the
    /// universal XCFramework.
    public struct ForeignBuild: Codable, Equatable, Sendable {
        public let inputs: [Input]

        /// The directory the build scripts run in. `nil` runs them in the project directory.
        public let workingDirectory: Path?

        /// The universal XCFramework build, produced when warming the binary cache.
        public let xcframework: XCFramework

        /// The thinner XCFramework build, produced during regular generation. `nil` falls back to the
        /// universal `xcframework` build.
        public let developmentXCFramework: XCFramework?

        /// Describes an input that affects a foreign build dependency's output.
        ///
        /// Inputs serve two purposes:
        /// - **Build phase input file list**: file, folder, and glob inputs are passed as input paths to the Xcode
        ///   build phase so that Xcode can skip re-running the script when inputs haven't changed.
        /// - **Content hashing**: all inputs (including scripts) are used to compute a content hash for Tuist's
        ///   binary caching and selective testing, so that the foreign build step can be skipped when inputs are unchanged.
        ///
        /// > Important: If folder/glob inputs resolve to no files, Xcode has nothing to track for incremental
        /// > builds, and the foreign build script is marked as always out-of-date so it re-runs on every build.
        /// > This is fine when the underlying build system (Gradle, Cargo, CMake, …) handles its own
        /// > incrementality; otherwise, double-check the configured paths.
        public enum Input: Codable, Hashable, Sendable {
            /// A single file whose contents affect the build output.
            case file(Path)

            /// A folder whose contents (recursively) affect the build output.
            case folder(Path)

            /// A glob pattern that resolves to files whose contents affect the build output.
            case glob(Path)

            /// A shell script whose stdout produces a cache key component (e.g. `"git rev-parse HEAD"`).
            ///
            /// Script inputs only contribute to the content hash and are not included in the build phase input file list.
            case script(String)
        }

        /// Describes how a binary artifact is linked.
        public enum Linking: String, Codable, Hashable, Sendable {
            case `static`, dynamic

            var product: Product {
                self == .static ? .staticFramework : .framework
            }
        }

        /// An XCFramework build: the script that produces it and where it lands.
        public struct XCFramework: Codable, Equatable, Sendable {
            /// The shell script that builds the XCFramework.
            public let script: String
            /// The path where the script produces the XCFramework. Tuist captures it for the cache and links it.
            public let path: Path
            /// Whether the artifact is statically or dynamically linked.
            public let linking: Linking
        }

        /// Describes the binary artifact produced by a foreign (non-Xcode) build system.
        public enum Output: Codable, Hashable, Sendable {
            /// An XCFramework output.
            ///
            /// - Parameters:
            ///   - path: Relative path to the xcframework.
            ///   - linking: Whether the xcframework is statically or dynamically linked.
            case xcframework(path: Path, linking: Linking)

            var product: Product {
                switch self {
                case let .xcframework(_, linking):
                    return linking.product
                }
            }
        }
    }

    /// Creates a foreign build target that wraps a non-Xcode build system (KMP, Rust, CMake, etc.).
    ///
    /// The target will become an aggregate target that runs the build script and produces the output binary.
    /// Other targets can depend on this target using `.target(name:)`.
    ///
    /// ### Example: Kotlin Multiplatform (KMP)
    ///
    /// ```swift
    /// .foreignBuild(
    ///     name: "SharedKMP",
    ///     destinations: .iOS,
    ///     script: """
    ///         eval "$($HOME/.local/bin/mise activate -C $SRCROOT bash --shims)"
    ///         cd $SRCROOT/SharedKMP && gradle assembleSharedKMPReleaseXCFramework
    ///         """,
    ///     inputs: [
    ///         .folder("SharedKMP/src"),
    ///         .file("SharedKMP/build.gradle.kts"),
    ///     ],
    ///     output: .xcframework(
    ///         path: "SharedKMP/build/XCFrameworks/release/SharedKMP.xcframework",
    ///         linking: .dynamic
    ///     )
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - name: A unique name for this foreign build target.
    ///   - destinations: The destinations this target supports.
    ///   - script: The shell script that builds the artifact. Runs in a shell build phase with `$SRCROOT` set to the project
    /// directory.
    ///   - inputs: Inputs that affect the build output, used for the build phase input file list and content hashing.
    ///   - output: The binary artifact produced by the script.
    ///   - metadata: The target's metadata.
    public static func foreignBuild(
        name: String,
        destinations: Destinations,
        script: String,
        inputs: [ForeignBuild.Input] = [],
        output: ForeignBuild.Output,
        metadata: TargetMetadata = .default
    ) -> Self {
        let path: Path
        let linking: ForeignBuild.Linking
        switch output {
        case let .xcframework(outputPath, outputLinking):
            path = outputPath
            linking = outputLinking
        }
        var target = self.init(
            name: name,
            destinations: destinations,
            product: output.product,
            productName: nil,
            bundleId: "tuist.foreign-build.\(name)",
            deploymentTargets: nil,
            infoPlist: nil,
            sources: nil,
            resources: nil,
            copyFiles: nil,
            headers: nil,
            entitlements: nil,
            scripts: [],
            dependencies: [],
            settings: nil,
            coreDataModels: [],
            environmentVariables: [:],
            launchArguments: [],
            additionalFiles: [],
            buildRules: [],
            mergedBinaryType: .disabled,
            mergeable: false,
            onDemandResourcesTags: nil,
            metadata: metadata,
            buildableFolders: []
        )
        target.foreignBuild = ForeignBuild(
            inputs: inputs,
            workingDirectory: nil,
            xcframework: ForeignBuild.XCFramework(script: script, path: path, linking: linking),
            developmentXCFramework: nil
        )
        return target
    }

    /// Creates a target that integrates a Kotlin Multiplatform framework built with Gradle.
    ///
    /// The target becomes an aggregate target that builds the Kotlin XCFramework. Other targets depend
    /// on it with `.target(name:)`.
    ///
    /// Tuist owns the build strategy: when warming the binary cache it runs `compileKotlinXCFrameworkScript`
    /// to build the universal XCFramework (all slices). During regular generation, if a development build
    /// is declared, it runs `compileKotlinDevelopmentXCFrameworkScript` to build a thinner XCFramework for
    /// the current destination instead, so local iteration is fast. Both are XCFrameworks, so consumers
    /// link and embed them the same way at any dependency depth. You don't choose; Tuist picks per context.
    ///
    /// ### Example
    ///
    /// ```swift
    /// .kotlinMultiplatform(
    ///     name: "SharedKMP",
    ///     destinations: .iOS,
    ///     gradleProject: "SharedKMP",
    ///     compileKotlinXCFrameworkScript: "gradle assembleSharedKMPReleaseXCFramework",
    ///     xcframeworkPath: "SharedKMP/build/XCFrameworks/release/SharedKMP.xcframework",
    ///     compileKotlinDevelopmentXCFrameworkScript: "gradle assembleSharedKMPDebugXCFramework",
    ///     developmentXCFrameworkPath: "SharedKMP/build/XCFrameworks/debug/SharedKMP.xcframework",
    ///     inputs: [
    ///         .folder("SharedKMP/src"),
    ///         .file("SharedKMP/build.gradle.kts"),
    ///     ]
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - name: A unique name for this target. Consumers depend on it with `.target(name:)`.
    ///   - destinations: The destinations the framework supports.
    ///   - gradleProject: Directory the build scripts run in (where the Gradle wrapper and the framework's module live).
    ///   - linking: How consumers link the framework. Defaults to `.dynamic`.
    ///   - compileKotlinXCFrameworkScript: Builds the universal XCFramework, used when warming the binary cache.
    ///   - xcframeworkPath: Where `compileKotlinXCFrameworkScript` produces the XCFramework. Tuist captures it for the cache and
    /// links it.
    ///   - compileKotlinDevelopmentXCFrameworkScript: Builds a thinner XCFramework for the current destination, used during
    /// regular generation. When omitted, regular generation falls back to the universal build.
    ///   - developmentXCFrameworkPath: Where `compileKotlinDevelopmentXCFrameworkScript` produces the XCFramework. Required when
    /// the development script is set.
    ///   - inputs: Inputs that affect the build output, used for the build phase input file list and content hashing.
    ///   - metadata: The target's metadata.
    public static func kotlinMultiplatform(
        name: String,
        destinations: Destinations,
        gradleProject: Path,
        linking: ForeignBuild.Linking = .dynamic,
        compileKotlinXCFrameworkScript: String,
        xcframeworkPath: Path,
        compileKotlinDevelopmentXCFrameworkScript: String? = nil,
        developmentXCFrameworkPath: Path? = nil,
        inputs: [ForeignBuild.Input] = [],
        metadata: TargetMetadata = .default
    ) -> Self {
        var target = self.init(
            name: name,
            destinations: destinations,
            product: linking.product,
            productName: nil,
            bundleId: "tuist.foreign-build.\(name)",
            deploymentTargets: nil,
            infoPlist: nil,
            sources: nil,
            resources: nil,
            copyFiles: nil,
            headers: nil,
            entitlements: nil,
            scripts: [],
            dependencies: [],
            settings: nil,
            coreDataModels: [],
            environmentVariables: [:],
            launchArguments: [],
            additionalFiles: [],
            buildRules: [],
            mergedBinaryType: .disabled,
            mergeable: false,
            onDemandResourcesTags: nil,
            metadata: metadata,
            buildableFolders: []
        )
        let developmentXCFramework = compileKotlinDevelopmentXCFrameworkScript.flatMap { developmentScript in
            developmentXCFrameworkPath.map { developmentPath in
                ForeignBuild.XCFramework(script: developmentScript, path: developmentPath, linking: linking)
            }
        }
        target.foreignBuild = ForeignBuild(
            inputs: inputs,
            workingDirectory: gradleProject,
            xcframework: ForeignBuild.XCFramework(
                script: compileKotlinXCFrameworkScript,
                path: xcframeworkPath,
                linking: linking
            ),
            developmentXCFramework: developmentXCFramework
        )
        return target
    }

    public static func target(
        name: String,
        destinations: Destinations,
        product: Product,
        productName: String? = nil,
        bundleId: String,
        deploymentTargets: DeploymentTargets? = nil,
        infoPlist: InfoPlist? = .default,
        sources: SourceFilesList? = nil,
        resources: ResourceFileElements? = nil,
        buildableFolders: [BuildableFolder] = [],
        copyFiles: [CopyFilesAction]? = nil,
        headers: Headers? = nil,
        entitlements: Entitlements? = nil,
        scripts: [TargetScript] = [],
        dependencies: [TargetDependency] = [],
        settings: Settings? = nil,
        coreDataModels: [CoreDataModel] = [],
        environmentVariables: [String: EnvironmentVariable] = [:],
        launchArguments: [LaunchArgument] = [],
        additionalFiles: [FileElement] = [],
        buildRules: [BuildRule] = [],
        mergedBinaryType: MergedBinaryType = .disabled,
        mergeable: Bool = false,
        onDemandResourcesTags: OnDemandResourcesTags? = nil,
        metadata: TargetMetadata = .default
    ) -> Self {
        self.init(
            name: name,
            destinations: destinations,
            product: product,
            productName: productName,
            bundleId: bundleId,
            deploymentTargets: deploymentTargets,
            infoPlist: infoPlist,
            sources: sources,
            resources: resources,
            copyFiles: copyFiles,
            headers: headers,
            entitlements: entitlements,
            scripts: scripts,
            dependencies: dependencies,
            settings: settings,
            coreDataModels: coreDataModels,
            environmentVariables: environmentVariables,
            launchArguments: launchArguments,
            additionalFiles: additionalFiles,
            buildRules: buildRules,
            mergedBinaryType: mergedBinaryType,
            mergeable: mergeable,
            onDemandResourcesTags: onDemandResourcesTags,
            metadata: metadata,
            buildableFolders: buildableFolders
        )
    }
}
