#!/bin/sh

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

generate_docs() {
  bundle exec rake docs
  git commit --message "Travis generated docs: $TRAVIS_BUILD_NUMBER"
}

upload_files() {
  git remote add origin-travis https://${GH_TOKEN}@github.com/xcbuddy/xcbuddy.git > /dev/null 2>&1
  git push --quiet --set-upstream origin-travis master 
}

setup_git
generate_docs
upload_files