default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tuist_lab_development
  url: <%= ENV['DATABASE_URL'] %>
test:
  <<: *default
  database: tuist_lab_test
  url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  url: <%= ENV['DATABASE_URL'] %>
