/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.tuist.gradle.api.model

import dev.tuist.gradle.api.model.CompleteShardUploadParams1PartsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param parts The uploaded parts with their ETags.
 * @param reference The shard plan reference.
 * @param uploadId The multipart upload ID.
 */


data class CompleteShardUploadParams1 (

    /* The uploaded parts with their ETags. */
    @SerializedName("parts")
    val parts: kotlin.collections.List<CompleteShardUploadParams1PartsInner>,

    /* The shard plan reference. */
    @SerializedName("reference")
    val reference: kotlin.String,

    /* The multipart upload ID. */
    @SerializedName("upload_id")
    val uploadId: kotlin.String

) {


}

