/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.tuist.gradle.api.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param partNumber The part number.
 * @param planId The shard plan identifier.
 * @param uploadId The multipart upload ID.
 */


data class GenerateShardUploadURLParams1 (

    /* The part number. */
    @SerializedName("part_number")
    val partNumber: kotlin.Int,

    /* The shard plan identifier. */
    @SerializedName("plan_id")
    val planId: kotlin.String,

    /* The multipart upload ID. */
    @SerializedName("upload_id")
    val uploadId: kotlin.String

) {


}

