defmodule Tuist.MCP.Server do
  @moduledoc false

  use EMCP.Server,
    name: "tuist",
    version: "1.6.1",
    tools: [
      Tuist.MCP.Components.Tools.ListXcodeBuilds,
      Tuist.MCP.Components.Tools.GetXcodeBuild,
      Tuist.MCP.Components.Tools.ListXcodeBuildTargets,
      Tuist.MCP.Components.Tools.ListXcodeBuildFiles,
      Tuist.MCP.Components.Tools.ListXcodeBuildIssues,
      Tuist.MCP.Components.Tools.ListXcodeBuildCacheTasks,
      Tuist.MCP.Components.Tools.ListXcodeBuildCASOutputs,
      Tuist.MCP.Components.Tools.ListGradleBuilds,
      Tuist.MCP.Components.Tools.GetGradleBuild,
      Tuist.MCP.Components.Tools.ListGradleBuildTasks,
      Tuist.MCP.Components.Tools.ListTestRuns,
      Tuist.MCP.Components.Tools.ListTestModuleRuns,
      Tuist.MCP.Components.Tools.ListTestSuiteRuns,
      Tuist.MCP.Components.Tools.ListTestCaseRuns,
      Tuist.MCP.Components.Tools.ListTestCases,
      Tuist.MCP.Components.Tools.ListTestCaseEvents,
      Tuist.MCP.Components.Tools.GetTestCase,
      Tuist.MCP.Components.Tools.UpdateTestCase,
      Tuist.MCP.Components.Tools.GetTestRun,
      Tuist.MCP.Components.Tools.GetTestCaseRun,
      Tuist.MCP.Components.Tools.ListTestCaseRunAttachments,
      Tuist.MCP.Components.Tools.ListBundles,
      Tuist.MCP.Components.Tools.GetBundle,
      Tuist.MCP.Components.Tools.GetBundleArtifactTree,
      Tuist.MCP.Components.Tools.ListGenerations,
      Tuist.MCP.Components.Tools.GetGeneration,
      Tuist.MCP.Components.Tools.ListCacheRuns,
      Tuist.MCP.Components.Tools.GetCacheRun,
      Tuist.MCP.Components.Tools.ListXcodeModuleCacheTargets,
      Tuist.MCP.Components.Tools.ListXcodeTestTargets,
      Tuist.MCP.Components.Tools.ListProjects
    ],
    prompts: [
      Tuist.MCP.Components.Prompts.FixFlakyTest,
      Tuist.MCP.Components.Prompts.CompareBuilds,
      Tuist.MCP.Components.Prompts.CompareTestRuns,
      Tuist.MCP.Components.Prompts.CompareBundles,
      Tuist.MCP.Components.Prompts.CompareTestCase,
      Tuist.MCP.Components.Prompts.CompareGenerations,
      Tuist.MCP.Components.Prompts.CompareCacheRuns,
      Tuist.MCP.Components.Prompts.AnalyzeSelectiveTesting
    ]
end
