import Foundation
import XCTest
@testable import ProjectDescription

final class ConfigTests: XCTestCase {
    func test_config_toJSON() throws {
        let config = Config(cloudURL: "https://tuist.io",
                            generationOptions: [
                                .xcodeProjectName("someprefix-\(.projectName)"),
                                .organizationName("TestOrg"),
                                .disableAutogeneratedSchemes,
                            ])

        XCTAssertCodable(config)
    }

    func test_config_toJSON_withAutogeneratedSchemes() throws {
        let config = Config(cloudURL: "https://tuist.io",
                            generationOptions: [
                                .xcodeProjectName("someprefix-\(.projectName)"),
                                .organizationName("TestOrg"),
                            ])

        XCTAssertCodable(config)
    }
}
