{
 "title": "Tuist - PromEx Oban Dashboard",
 "description": "All the data that is presented here is captured by the PromEx Oban plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/oban.ex)",
 "tags": [
  "PromEx",
  "Oban",
  "tuist"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(tuist_oban_queue_length_count, job)"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(tuist_oban_queue_length_count{job=\"$job\"}, env)"
   },
   {
    "name": "oban",
    "label": "Oban Instance",
    "query": "label_values(tuist_oban_queue_length_count, name)"
   },
   { "name": "interval", "label": "Interval", "query": "1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Jobs in Queue",
   "type": "bargauge",
   "description": "The number of jobs in each queue that are in the available state.",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (tuist_oban_queue_length_count{job=\"$job\", env=\"$env\", name=\"$oban\", state=\"available\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Processed Jobs (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs processed across all queues and states.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(tuist_oban_job_processing_duration_milliseconds_count{env=\"$env\", job=\"$job\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Job Errors (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs that resulted in an error across all queues.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(tuist_oban_job_exception_duration_milliseconds_count{env=\"$env\", job=\"$job\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Jobs Enqueued (by $interval interval)",
   "type": "stat",
   "description": "The number of jobs that have been enqueued.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(tuist_oban_producer_dispatched_count_count{env=\"$env\", job=\"$job\", name=\"$oban\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Successful Job Processing Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Job Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to process jobs across all queues.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_job_processing_duration_milliseconds_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Job Queue Time",
   "type": "heatmap",
   "description": "A heatmap showing how long jobs are waiting in queue for processing.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_job_queue_time_milliseconds_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Job Execution Time",
   "type": "graph",
   "description": "The average time it took to process jobs per queue. This will include jobs that ended with a successful, snoozed, or discarded state.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "Execution Time" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_processing_duration_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_processing_duration_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  {
   "title": "Average Job Queue Time",
   "type": "graph",
   "description": "The average time a job waited in queue for processing.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "In Queue Time" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_queue_time_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_queue_time_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  {
   "title": "Average Job Attempts",
   "type": "graph",
   "description": "The average time it took to process jobs per queue. This will include jobs that ended with a successful, snoozed, or discarded state.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "locale", "label": "Job Attempts" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_complete_attempts_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_complete_attempts_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  { "title": "Job Error Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Job Execution Time",
   "type": "heatmap",
   "description": "A heatmap showing the time it took to process jobs across all queues that resulted in an error.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_job_exception_duration_milliseconds_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Job Queue Time",
   "type": "heatmap",
   "description": "A heatmap showing how long jobs are waiting in queue for processing that resulted in an error.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_job_exception_queue_time_milliseconds_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Job Execution Time",
   "type": "graph",
   "description": "The average time it took to process jobs per queue that resulted in an error.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms", "label": "Execution Time" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_exception_duration_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_exception_duration_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ error }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  {
   "title": "Average Job Queue Time",
   "type": "graph",
   "description": "The average time a job waited in queue for processing prior to resulting in an error.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "ms", "label": "In Queue Time" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_exception_queue_time_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_exception_queue_time_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ error }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  {
   "title": "Average Job Failure Attempts",
   "type": "graph",
   "description": "The average time it took to process jobs per queue that resulted in an error.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "locale", "label": "Job Attempts" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_job_exception_attempts_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_job_exception_attempts_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "({{ state }}) {{ name }} :: {{ worker }}"
    }
   ]
  },
  { "title": "Queue Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Available Jobs per Queue",
   "type": "graph",
   "description": "The number of jobs marked as available in each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (tuist_oban_queue_length_count{job=\"$job\", env=\"$env\", name=\"$oban\", state=\"available\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Completed Jobs per Queue",
   "type": "graph",
   "description": "The number of jobs marked as completed in each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (tuist_oban_queue_length_count{job=\"$job\", env=\"$env\", name=\"$oban\", state=\"completed\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Executing Jobs per Queue",
   "type": "graph",
   "description": "The number of jobs marked as executing in each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (tuist_oban_queue_length_count{job=\"$job\", env=\"$env\", name=\"$oban\", state=\"executing\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Retryable Jobs per Queue",
   "type": "graph",
   "description": "The number of jobs marked as retryable in each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (tuist_oban_queue_length_count{job=\"$job\", env=\"$env\", name=\"$oban\", state=\"retryable\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  { "title": "Producer Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Producer Dispatch Time",
   "type": "heatmap",
   "description": "A heatmap showing how long jobs to be dispatched.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_producer_duration_milliseconds_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Producer Dispatch Count",
   "type": "heatmap",
   "description": "A heatmap showing the number of jobs that were dispatched.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "sum(irate(tuist_oban_producer_dispatched_count_bucket{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Dispatch Time",
   "type": "graph",
   "description": "The average amount of time it took to dispatch jobs to each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "ms", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_producer_duration_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_producer_duration_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Average Dispatch Count",
   "type": "graph",
   "description": "The average number of jobs dispatched to each queue.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "short", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_producer_dispatched_count_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_producer_dispatched_count_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Average Exception Duration",
   "type": "graph",
   "description": "The average amount of time it took to encounter an encounter an error.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "ms", "label": "Number of Jobs" }
   ],
   "targets": [
    {
     "expr": "irate(tuist_oban_producer_exception_duration_milliseconds_sum{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]) / irate(tuist_oban_producer_exception_duration_milliseconds_count{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval])",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  { "title": "Circuit Breaker Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Circuit Trip Events (last 1 hour)",
   "type": "stat",
   "description": "This is the total number of trip events that have been encountered by the selected application and Oban instances.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 161 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tuist_oban_circuit_trip_total{job=\"$job\", env=\"$env\", name=\"$oban\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Circuit Trip Events",
   "type": "stat",
   "description": "This is the total number of trip events that have been encountered by the selected application and Oban instances.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 161 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tuist_oban_circuit_trip_total{job=\"$job\", env=\"$env\", name=\"$oban\"})"
    }
   ]
  },
  {
   "title": "Circuit Open Events (last 1 hour)",
   "type": "stat",
   "description": "This is the total number of open events that have been encountered by the selected application and Oban instances.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 161 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tuist_oban_circuit_open_total{job=\"$job\", env=\"$env\", name=\"$oban\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Circuit Open Events",
   "type": "stat",
   "description": "This is the total number of open events that have been encountered by the selected application and Oban instances.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 161 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tuist_oban_circuit_open_total{job=\"$job\", env=\"$env\", name=\"$oban\"})"
    }
   ]
  },
  {
   "title": "Circuit Breaker Trip Events",
   "type": "graph",
   "description": "The number of circuit breaker trip events that occurred along with what component tripped the breaker.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short", "label": "Number of Circuit Trips" }
   ],
   "targets": [
    {
     "expr": "sum by (circuit_breaker) (increase(tuist_oban_circuit_trip_total{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]))",
     "legendFormat": "{{ circuit_breaker }}"
    }
   ]
  },
  {
   "title": "Circuit Breaker Open Events",
   "type": "graph",
   "description": "The number of circuit breaker open events that occurred along with what component tripped the breaker.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short", "label": "Number of Circuit Opens" }
   ],
   "targets": [
    {
     "expr": "sum by (circuit_breaker) (increase(tuist_oban_circuit_open_total{job=\"$job\", env=\"$env\", name=\"$oban\"}[$interval]))",
     "legendFormat": "{{ circuit_breaker }}"
    }
   ]
  }
 ]
}