Mimic.copy(Sentry)
Mimic.copy(TuistRegistry.Config)
Mimic.copy(ExAws.S3.Upload)
Mimic.copy(ExAws.S3)
Mimic.copy(ExAws)
Mimic.copy(ExAws.Config)
Mimic.copy(TuistRegistry.S3)
Mimic.copy(Plug.Conn)
Mimic.copy(Req)
Mimic.copy(OpenTelemetry.Tracer)
Mimic.copy(TuistRegistry.Swift.Metadata)
Mimic.copy(TuistRegistry.Swift.AlternateManifests)
Mimic.copy(TuistCommon.GitHub)

ExUnit.start(max_cases: min(System.schedulers_online(), 4))
