alias TuistRegistry.Swift.Disk

Mimic.copy(Sentry)
Mimic.copy(TuistRegistry.Config)
Mimic.copy(Disk)
Mimic.copy(Disk)
Mimic.copy(TuistRegistry.CacheArtifacts)
Mimic.copy(ExAws.S3.Upload)
Mimic.copy(ExAws.S3)
Mimic.copy(ExAws)
Mimic.copy(ExAws.Config)
Mimic.copy(TuistRegistry.S3)
Mimic.copy(TuistRegistry.S3Transfers)
Mimic.copy(Plug.Conn)
Mimic.copy(Req)
Mimic.copy(OpenTelemetry.Tracer)
Mimic.copy(TuistRegistry.Swift.Metadata)
Mimic.copy(TuistRegistry.Swift.AlternateManifests)
Mimic.copy(TuistCommon.GitHub)
Mimic.copy(TuistRegistry.Swift.Lock)
Mimic.copy(TuistRegistry.Swift.SwiftPackageIndex)
Mimic.copy(TuistRegistry.Swift.SyncCursor)
Mimic.copy(TuistRegistry.CacheArtifactsBuffer)
Mimic.copy(TuistRegistry.S3TransfersBuffer)
Mimic.copy(TuistRegistry.Repo)
Mimic.copy(TuistRegistry.AnalyticsCircuitBreaker)

ExUnit.start(max_cases: min(System.schedulers_online(), 4))
