import Foundation

// MARK: - Workspace

public struct Workspace: Codable, Equatable {
    /// Contains options related to the workspace generation.
    public enum GenerationOption: Codable, Equatable {
        /// Represents the behavior Xcode will apply to the workspace regarding
        /// schema generation using the `IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded` key.
        /// - seealso: `WorkspaceSettingsDescriptor`
        public enum AutomaticXcodeSchemes: String, Codable, Equatable {
            /// Will add the key with the value set to `true`.
            case enabled

            /// Will add the key with the value set to `false`.
            case disabled
        }

        /// Contains options for the autogenerated wotkspace schemes
        public enum AutogeneratedWorkspaceSchemes: Codable, Equatable {
            /// Contains options for code coverage
            public enum CodeCoverageMode: Codable, Equatable {
                /// Gather code coverage for all targets
                case all
                /// Gather code coverage only for targets, that have code coverage enabled at least in one scheme
                case relevant
                /// Gather code coverage only for given targets
                case targets([TargetReference])
                /// Do not gather code coverage
                case disabled
            }

            /// Tuist will not automatically generate the workspace schemes
            case disabled
            /// Tuist will generate the workspace schemes
            case enabled(codeCoverageMode: CodeCoverageMode = .disabled, testingOptions: TestingOptions = [])
        }

        /// Tuist generates a WorkspaceSettings.xcsettings file, setting the related key to the associated value.
        case automaticXcodeSchemes(AutomaticXcodeSchemes)

        /// Options controlling how / if Tuist automatically generates the workspace scheme.
        /// Default value when not set is `.autogeneratedWorkspaceSchemes(.enabled([]))`
        case autogeneratedWorkspaceSchemes(AutogeneratedWorkspaceSchemes)
    }

    /// Name of the workspace
    public let name: String

    /// List of project relative paths (or glob patterns) to generate and include
    public let projects: [Path]

    /// List of custom schemes
    public let schemes: [Scheme]

    /// Default file header template used for Xcode file templates
    public let fileHeaderTemplate: FileHeaderTemplate?

    /// List of files to include in the workspace (e.g. Documentation)
    public let additionalFiles: [FileElement]

    /// Generation options.
    public let generationOptions: [GenerationOption]

    /// Workspace
    ///
    /// This can be used to customize the generated workspace.
    ///
    /// - Parameters:
    ///   - name: Name of the workspace.
    ///   - projects: List of project relative paths (or glob patterns) to generate and include.
    ///   - additionalFiles: List of files to include in the workspace (e.g. Documentation)
    public init(
        name: String,
        projects: [Path],
        schemes: [Scheme] = [],
        fileHeaderTemplate: FileHeaderTemplate? = nil,
        additionalFiles: [FileElement] = [],
        generationOptions: [GenerationOption] = []
    ) {
        self.name = name
        self.projects = projects
        self.schemes = schemes
        self.fileHeaderTemplate = fileHeaderTemplate
        self.additionalFiles = additionalFiles
        self.generationOptions = generationOptions
        dumpIfNeeded(self)
    }
}
