# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::ApiRendering`.
# Please instead update this file by running `bin/tapioca dsl ActionController::ApiRendering`.

module ActionController::ApiRendering
  mixes_in_class_methods ::ActionView::ViewPaths::ClassMethods
  mixes_in_class_methods ::ActionView::Rendering::ClassMethods
end
