name: Backbone deploy

on:
  push:
    branches:
      - main

concurrency:
  group: backbone-deploy-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        env:
          BACKBONE_HEROKU_API_TOKEN: ${{ secrets.BACKBONE_HEROKU_API_TOKEN }}
          BACKBONE_HEROKU_APP_NAME: 'tuist-backbone'
        run: |
          git remote add heroku https://heroku:$BACKBONE_HEROKU_API_TOKEN@git.heroku.com/$BACKBONE_HEROKU_APP_NAME.git
          git push heroku  --force HEAD:main