name: Backbone

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - projects/backbone/**
      - projects/fourier/**
env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.BACKBONE_RAILS_MASTER_KEY }}
  RUBY_VERSION: 3.0.3

concurrency:
  group: backbone-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:4.0.6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-${{ hashFiles('project/backbone/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
      - name: Install dependencies
        working-directory: projects/backbone
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs=4 --retry=3
      - name: Set up database (to detect schema breaking changes)
        working-directory: projects/backbone
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Test
        working-directory: projects/backbone
        run: |
          bundle exec rails test
  lint:
    name: Lint
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.RUBY_VERSION }}${{ hashFiles('project/backbone/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Install Bundler dependencies
        run: bundle install
      - name: Run
        run: ./fourier lint backbone

  assets_precompile:
    name: Assets precompile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-${{ hashFiles('project/backbone/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
      - name: Install dependencies
        working-directory: projects/backbone
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs=4 --retry=3
      - name: Assets precompile
        working-directory: projects/backbone
        run: |
          bundle exec rails assets:precompile
