name: Tuist Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - projects/tuistbench/**

env:
  TUIST_STATS_OPT_OUT: true
  RUBY_VERSION: '2.7.2'

jobs:
  test:
    name: Build benchmarking tooling with Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['12', '12.4']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build
        run: ./fourier build benchmark
