name: conventional-pr
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr:
    name: Lint PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2
      - uses: amannn/action-semantic-pull-request@e32d7e603df1aa1ba07e981f2a23455dee596825 #v5
        with:
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
