name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Create a new release
        uses: fortmarek/tapestry-action@0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}