name: Cloud

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Sha of the commit to be deployed
        required: true

concurrency:
  group: staging-deployment-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    environment:
      name: staging
      url: https://cloud-staging.tuist.io
    name: Staging Deployment
    env:
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy -c fly.staging.toml --build-arg RAILS_ENV=staging --wait-timeout 600
