name: Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_sha:
        description: The commit SHA to deploy. When not passed, it deploys the latest commit available in `main`.
        required: false

concurrency:
  group: canary-deployment-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    environment:
      name: canary
      url: https://cloud-canary.tuist.io
    name: Canary Deployment
    env:
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha == '' }}
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha != '' }}
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy -c fly.canary.toml --build-arg RAILS_ENV=canary --wait-timeout 600
