name: 'Deploy dry run'

on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group: {}

concurrency:
  group: deploy-dry-run-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy dry run
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --build-only
