name: Cloud Canary Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_sha:
        description: The commit SHA to deploy. When not passed, it deploys the latest commit available in `main`.
        required: false

concurrency:
  group: deployment-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }}

jobs:
  canary:
    environment:
      name: canary
      url: https://cloud-canary.tuist.io
    name: Canary Deployment
    env:
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha == '' }}
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha != '' }}
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy --remote-only -c fly.canary.toml --build-arg RAILS_ENV=canary --wait-timeout 3600
  acceptance-tests:
    name: Acceptance Tests
    runs-on: macos-13
    timeout-minutes: 20
    needs: canary
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tuist/tuist-cloud
          token: ${{ secrets.TUIST_CLOUD_TOKEN }}
      - uses: asdf-vm/actions/install@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      - uses: actions/cache@v3
        name: 'Cache fetched dependencies folder'
        with:
          path: Tuist/Dependencies/SwiftPackageManager/.build
          key: spm-v1-${{ hashFiles('Package.resolved') }}
          restore-keys: spm-v1-${{ hashFiles('Package.resolved') }}
      - name: Fetch dependencies
        run: tuist fetch
      - name: Test
        run: tuist test TuistCloudAcceptanceTests --test-targets TuistCloudAcceptanceTests/TuistCloudAcceptanceTestWithIOSAppWithFrameworks
  production:
    environment:
      name: production
      url: https://cloud.tuist.io
    name: Production Deployment
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: acceptance-tests
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha == '' }}
      - uses: actions/checkout@v3
        if: ${{ github.event.inputs.commit_sha != '' }}
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy --remote-only -c fly.toml --build-arg RAILS_ENV=production --wait-timeout 3600


