name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    name: Deploy staging app
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # We deploy first to staging to give some window to test the changes
      - name: Deploy staging
        run: flyctl deploy -c fly.staging.toml --build-arg RAILS_ENV=staging --wait-timeout 600
  deploy:
    name: Deploy app
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 40
    # We deploy first to staging to give some window to test the changes
    needs: deploy-staging
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only --wait-timeout 600
  docker:
    name: Push docker image
    env:
      DOCKER_BUILDKIT: 1
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

