name: Cloud Dry Run

on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group: {}

concurrency:
  group: cloud-dry-run-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          build-args: "RAILS_ENV=production"
          cache-from: type=gha
          cache-to: type=gha,mode=max
