name: handbook-deploy
on:
  push:
    branches:
      - "main"
    paths:
      - handbook/**
      - .github/workflows/handbook-deploy.yml
      - handbook/pnpm-lock.yaml
      - handbook/package.json

concurrency:
  group: handbook-deploy-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: handbook

env:
  PNPM_HOME: ~/.pnpm

jobs:
  handbook-deploy:
    name: Handbook Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('../pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Deploy handbook
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: mise run deploy
