name: Release

on:
  schedule:
    # Every Monday at 11:00
    - cron: '0 10 * * 1'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: read
  statuses: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - name: 'Get version'
        id: version
        run: |
          version=$(./script/generate_version.rb)
          echo "::set-output name=version::$version"
      - name: "Generate Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "tuist"
          repo: "cloud"
          configuration: ".github/changelog-configuration.json"
          toTag: "main"
          outputFile: README.md
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Single-line changelog
        id: single_line_changelog
        run: |
          changelog="${{ steps.changelog.outputs.changelog }}"
          single_line_changelog=$(echo "$changelog" | tr '\n' ' ')
          single_line_changelog="${single_line_changelog// /\\n}"
          echo "::set-output name=single_line_changelog::$single_line_changelog"
      - name: Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tuist/cloud
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=Tuist Cloud
            org.opencontainers.image.description=${{ steps.single_line_changelog.outputs.single_line_changelog }}
            org.opencontainers.image.vendor=Tuist GmbH
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     build-args: "TUIST_VERSION=\"${{ steps.version.outputs.version }}\",RAILS_ENV=production"
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     github-token: ${{ secrets.TUIST_CLOUD_RELEASE_TOKEN }}
      # - name: Create GitHub Release on tuist/cloud
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: false
      #     repository: tuist/cloud
      #     name: ${{ steps.version.outputs.version }}
      #     tag_name: ${{ steps.version.outputs.version }}
      #     body: ${{ steps.changelog.outputs.changelog }}
      #     token: ${{ secrets.TUIST_CLOUD_RELEASE_TOKEN }}

