name: Server Worker

on:
  push:
    branches:
      - main
    paths:
      - server/worker/**
      - .github/workflows/server-worker.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - server/worker/**
      - .github/workflows/server-worker.yml
      - pnpm-lock.yaml
  merge_group: {}

permissions:
  contents: read

concurrency:
  group: tuist-server-worker-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PNPM_HOME: ~/.pnpm
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

defaults:
  run:
    working-directory: server/worker

jobs:
  test:
    name: Test
    runs-on: namespace-profile-default
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore PNPM Cache
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-server-worker-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v3.2.0
        with:
          cache_key: "{{default}}-{{env.NSC_BASE_IMAGE_REF_ID}}"
      - run: mise install
      - run: pnpm install
      - run: pnpm run test
