name: Server Production Deployment

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: The commit SHA to deploy. When not passed, it deploys the latest commit available in `main`.
        required: false

permissions:
  contents: read

concurrency:
  group: server-production-hotfix-deployment-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_EXT_CONFIG_TOKEN }}
  MISE_EXPERIMENTAL: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PNPM_HOME: ~/.pnpm
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  production-hotfix:
    environment: server-production
    name: Hotfix Production Deployment
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: namespace-profile-default
    timeout-minutes: 60
    if: ${{ contains(github.event.head_commit.message, '(hotfix)') }}
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.commit_sha == '' }}
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.commit_sha != '' }}
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: "Get version"
        id: version
        run: |
          version=$(../mise/tasks/server/generate-version.sh)
          echo "::set-output name=version::$version"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy -c fly.prod.toml --build-arg TUIST_HOSTED=1 --build-arg MIX_ENV=prod --build-arg TUIST_VERSION=${{ steps.version.outputs.version }} --build-arg APP_REVISION=$GITHUB_SHA --wait-timeout 3600
      - name: Notify about the deployment in Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            commit: "${{ github.sha }}"
            environment: "production"
