name: Tuist

on:
  push:
    branches:
      - main
  pull_request:
  merge_group: {}

concurrency:
  group: tuist-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  MASTER_KEY: ${{ secrets.MASTER_KEY }}
  MISE_EXPERIMENTAL: "1"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PNPM_HOME: ~/.pnpm

jobs:
  check_locales_extraction:
    name: Check locales extraction
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Check if extraction is needed
        run: mix gettext.extract --check-up-to-date
      - name: Print instruction if extraction validation fails
        if: failure()
        run: echo "Run 'mix gettext.extract --merge --locale en'"
  test:
    name: Test
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    services:
      postgres:
        image: timescale/timescaledb-ha:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Run tests
        run: mix test
  analyze-migrations:
    name: Analyze migrations
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    services:
      postgres:
        image: timescale/timescaledb-ha:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Analyze migrations
        run: mix excellent_migrations.migrate
  credo:
    name: Credo
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Run Credo
        run: mix credo
  format:
    name: Format
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Check format
        run: mise run format --check
  security:
    name: Security
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Check
        run: mise run security
  build_on_premise_image:
    name: Build on-premise image
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            TUIST_HOSTED=0
            TUIST_VERSION=1.24.11.11
            MIX_ENV=prod
  seed:
    name: Seed
    runs-on: "blacksmith-4vcpu-ubuntu-2204"
    timeout-minutes: 15
    services:
      postgres:
        image: timescale/timescaledb-ha:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Restore Mix Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            _site
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Restore PNPM Cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm/store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: jdx/mise-action@v2
      - name: Run migrations
        run: mix ecto.migrate
      - name: Seed the database
        run: mix run priv/repo/seeds.exs
