name = "tuist-cas"
main = "src/index.js"
compatibility_date = "2025-01-08"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[vars]
# TUIST_S3_REGION = "us-east-1"
# TUIST_S3_ENDPOINT = "https://s3.amazonaws.com"
# TUIST_S3_BUCKET_NAME = "your-bucket-name"
# TUIST_S3_BUCKET_AS_HOST = "false"
# TUIST_S3_VIRTUAL_HOST = "false"

# Secrets (use: wrangler secret put TUIST_S3_ACCESS_KEY_ID)
# - TUIST_S3_ACCESS_KEY_ID
# - TUIST_S3_SECRET_ACCESS_KEY

[build]
command = ""

[env.production]
name = "tuist-cas-production"

[env.staging]
name = "tuist-cas-staging"
